---
title:                                  J1 Template Core
tagline:                                Layout, design and configuration
description:                            Base functions for layout, design and configuration

tags:                                   [ Template, Overview, Core ]
index:                                  []
categories:                             [ pages ]

permalink:                              /pages/public/panel/service_panel/core/
regenerate:                             false

resources:                              []
resource_options:
---

// Enable the Liquid Preprocessor 
// -----------------------------------------------------------------------------
:page-liquid:

// Set other global page attributes here
// -----------------------------------------------------------------------------
//:my-asciidoc-attribute:

//  Load Liquid procedures
// -----------------------------------------------------------------------------
{% capture set_env_entry_document %}themes/{{site.template.name}}/procedures/global/set_env_entry_document.proc{%endcapture%}
{% capture set_image_block %}themes/{{site.template.name}}/procedures/global/set_image_block.proc{%endcapture%}

// Initialize entry document environmental attributes
// -----------------------------------------------------------------------------
{% include {{set_env_entry_document}} %}

// Load tag, url and data attributes
// -----------------------------------------------------------------------------
include::{includedir}/attributes.asciidoc[tag=tags]
include::{includedir}/attributes.asciidoc[tag=urls]
include::{includedir}/attributes.asciidoc[tag=data]

// Set local page attributes
// -----------------------------------------------------------------------------
:images-dir:                            {imagesdir}/pages/roundtrip/100_present_images


== Core

The core integrates the site generator Jekyll into J1, contains all base
functions for layout pages, design and configuration. Provides procedures
to generate web pages automatically based on a given layout based on design
settings and your personal configuration.

=== Layout System

lorem:sentences[5]

:j1-page-layout-data: "pages/kickstarter/web_in_a_day/j1_layout.png, J1 Page Layout"
.J1 Page Layout
lightbox::theme-uno[ 700, {j1-page-layout-data} ]


=== Template Engine

lorem:sentences[3]

lorem:sentences[2]

=== Bootstrap Integration

See examples for Bootstrap’s powerful, responsive navigation header, the
navbar. Includes support for branding, navigation, and more, including
support for the collapse plugin.

pass:[<i class="mdi mdi-book-open mdi-24px mdi-md-bg-primary"></i>]
Refer to: link:{bs_doc_components_navbar}[Bootstrap Docs, {window}].

==== Navbars

++++
<!-- Navbar
============================================================================ -->
<div class="bs-docs-section clearfix">
  <div class="row mb-5">
    <div class="col-md-12">
      <div class="bs-component mb-2">
        <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
          <a class="navbar-brand" href="#">Navbar</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarColor01">
            <ul class="navbar-nav mr-auto">
              <li class="nav-item active">
                <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">Features</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">Pricing</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">About</a>
              </li>
            </ul>
            <form class="form-inline my-2 my-lg-0">
              <input class="form-control mr-sm-2" type="text" placeholder="Search">
              <button class="btn btn-secondary btn-raised my-2 my-sm-0" type="submit">Search</button>
            </form>
          </div>
        </nav>
      </div>
      <div class="bs-component mb-2">
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
          <a class="navbar-brand" href="#">Navbar</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor02" aria-controls="navbarColor02" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarColor02">
            <ul class="navbar-nav mr-auto">
              <li class="nav-item active">
                <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">Features</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">Pricing</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">About</a>
              </li>
            </ul>
            <form class="form-inline my-2 my-lg-0">
              <input class="form-control mr-sm-2" type="text" placeholder="Search">
              <button class="btn btn-secondary btn-raised my-2 my-sm-0" type="submit">Search</button>
            </form>
          </div>
        </nav>
      </div>
      <div class="bs-component mb-2">
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
          <a class="navbar-brand" href="#">Navbar</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor03" aria-controls="navbarColor03" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarColor03">
            <ul class="navbar-nav mr-auto">
              <li class="nav-item active">
                <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">Features</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">Pricing</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">About</a>
              </li>
            </ul>
            <form class="form-inline my-2 my-lg-0">
              <input class="form-control mr-sm-2" type="text" placeholder="Search">
              <button class="btn btn-secondary btn-raised my-2 my-sm-0" type="submit">Search</button>
            </form>
          </div>
        </nav>
      </div>
    </div>
  </div>
</div>
++++

==== Buttons

Use Bootstrap’s custom button styles for actions in forms, dialogs, and
more with support for multiple sizes, states, and more. Bootstrap includes
several predefined button styles, each serving its own semantic purpose,
with a few extras thrown in for more control.

pass:[<i class="mdi mdi-book-open mdi-24px mdi-md-bg-primary"></i>]
Refer to: link:{bs_doc_components_buttons}[Bootstrap Docs, {window}].

++++
<div class="bs-docs-section">
  <div class="row mb-4">
    <div class="col-md-10">
      <p class="bs-component">
        <button type="button" class="btn btn-primary btn-raised">
          Primary
      <div class="ripple-container"></div></button>
      <button type="button" class="btn btn-secondary btn-raised">Secondary</button>
      <button type="button" class="btn btn-success btn-raised">
        Success
        <div class="ripple-container"></div>
      </button>
      <button type="button" class="btn btn-info btn-raised">Info</button>
      <button type="button" class="btn btn-warning btn-raised">Warning</button>
      <button type="button" class="btn btn-danger btn-raised">Danger</button>
      <button type="button" class="btn btn-link btn-raised">Link</button>
      </p>
      <p class="bs-component">
        <button type="button" class="btn btn-primary btn-raised disabled">Primary</button>
        <button type="button" class="btn btn-secondary btn-raised disabled">Secondary</button>
        <button type="button" class="btn btn-success btn-raised disabled">Success</button>
        <button type="button" class="btn btn-info btn-raised disabled">Info</button>
        <button type="button" class="btn btn-warning btn-raised disabled">Warning</button>
        <button type="button" class="btn btn-danger btn-raised disabled">Danger</button>
        <button type="button" class="btn btn-link btn-raised disabled">Link</button>
      </p>
      <p class="bs-component">
        <button type="button" class="btn btn-outline-primary btn-raised">Primary</button>
        <button type="button" class="btn btn-outline-secondary btn-raised">Secondary</button>
        <button type="button" class="btn btn-outline-success btn-raised">Success</button>
        <button type="button" class="btn btn-outline-info btn-raised">Info</button>
        <button type="button" class="btn btn-outline-warning btn-raised">Warning</button>
        <button type="button" class="btn btn-outline-danger btn-raised">Danger</button>
      </p>
      <div class="bs-component">
        <div class="btn-group" role="group" aria-label="Button group with nested dropdown">
          <button type="button" class="btn btn-primary btn-raised">Primary</button>
          <div class="btn-group" role="group">
            <button id="btnGroupDrop1" type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"></button>
            <div class="dropdown-menu" aria-labelledby="btnGroupDrop1">
              <a class="dropdown-item" href="#">Dropdown link</a>
              <a class="dropdown-item" href="#">Dropdown link</a>
            </div>
          </div>
        </div>
        <div class="btn-group" role="group" aria-label="Button group with nested dropdown">
          <button type="button" class="btn btn-success btn-raised">Success</button>
          <div class="btn-group" role="group">
            <button id="btnGroupDrop2" type="button" class="btn btn-success dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <div class="ripple-container"></div>
            </button>
            <div class="dropdown-menu showing hiding" aria-labelledby="btnGroupDrop2" x-placement="bottom-start" style="position: absolute; will-change: top, left; top: 37px; left: 0px;">
              <a class="dropdown-item" href="#">Dropdown link</a>
              <a class="dropdown-item" href="#">
                Dropdown link
                <div class="ripple-container">
                  <div class="ripple-decorator ripple-on ripple-out" style="left: 79.1094px; top: 56.7656px; background-color: rgb(255, 255, 255); transform: scale(19.75);"></div>
                </div>
              </a>
            </div>
          </div>
        </div>
        <div class="btn-group" role="group" aria-label="Button group with nested dropdown">
          <button type="button" class="btn btn-info">Info</button>
          <div class="btn-group" role="group">
            <button id="btnGroupDrop3" type="button" class="btn btn-info dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"></button>
            <div class="dropdown-menu" aria-labelledby="btnGroupDrop3">
              <a class="dropdown-item" href="#">Dropdown link</a>
              <a class="dropdown-item" href="#">Dropdown link</a>
            </div>
          </div>
        </div>
        <div class="btn-group" role="group" aria-label="Button group with nested dropdown">
          <button type="button" class="btn btn-danger">Danger</button>
          <div class="btn-group" role="group">
            <button id="btnGroupDrop4" type="button" class="btn btn-danger dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"></button>
            <div class="dropdown-menu" aria-labelledby="btnGroupDrop4">
              <a class="dropdown-item" href="#">Dropdown link</a>
              <a class="dropdown-item" href="#">Dropdown link</a>
            </div>
          </div>
        </div>
      </div>
      <div class="bs-component mt-2">
        <button type="button" class="btn btn-primary btn-raised btn-lg">Large button</button>
        <button type="button" class="btn btn-primary btn-raised">Default button</button>
        <button type="button" class="btn btn-primary btn-raised btn-sm">Small button</button>
      </div>
    </div>
    <div class="col-md-12">
      <p class="bs-component mt-2">
        <button type="button" class="btn btn-primary btn-raised btn-lg btn-block">Block level button</button>
      </p>
      <div class="bs-component" style="margin-bottom: 15px;">
        <div class="btn-group" data-toggle="buttons">
          <label class="btn btn-primary btn-raised active">
          <input type="checkbox" checked=""> Checkbox 1
          </label>
          <label class="btn btn-primary btn-raised">
          <input type="checkbox"> Checkbox 2
          </label>
          <label class="btn btn-primary btn-raised">
          <input type="checkbox"> Checkbox 3
          </label>
        </div>
      </div>
      <div class="bs-component" style="margin-bottom: 15px;">
        <div class="btn-group" data-toggle="buttons">
          <label class="btn btn-primary btn-raised active">
          <input type="radio" name="options" id="option1" checked=""> Radio 1
          </label>
          <label class="btn btn-primary btn-raised">
          <input type="radio" name="options" id="option2"> Radio 2
          </label>
          <label class="btn btn-primary btn-raised">
          <input type="radio" name="options" id="option3"> Radio 3
          </label>
        </div>
      </div>
    </div>
  </div>
</div>
++++
