---
title:                                  J1 Template Modules
tagline:                                Ready-to-use Applications for your Web
description:                            Ready-to-use applications to present image and video content

tags:                                   [ Template, Overview, Modules ]
index:                                  []
categories:                             [ pages ]

permalink:                              /pages/public/panel/service_panel/modules/
regenerate:                             false

resources:                              [
                                          carousel, justified_gallery,
                                          lightbox, light_gallery, bs_gallery
                                        ]
resource_options:
---

// Enable the Liquid Preprocessor 
// -----------------------------------------------------------------------------
:page-liquid:

// Set other global page attributes here
// -----------------------------------------------------------------------------
//:my-asciidoc-attribute:

//  Load Liquid procedures
// -----------------------------------------------------------------------------
{% capture set_env_entry_document %}themes/{{site.template.name}}/procedures/global/set_env_entry_document.proc{%endcapture%}
{% capture set_image_block %}themes/{{site.template.name}}/procedures/global/set_image_block.proc{%endcapture%}

// Initialize entry document environmental attributes
// -----------------------------------------------------------------------------
{% include {{set_env_entry_document}} %}

// Load tag, url and data attributes
// -----------------------------------------------------------------------------
include::{includedir}/attributes.asciidoc[tag=tags]
include::{includedir}/attributes.asciidoc[tag=urls]
include::{includedir}/attributes.asciidoc[tag=data]

// Set local page attributes
// -----------------------------------------------------------------------------
:images-dir:                            {imagesdir}/pages/roundtrip/100_present_images


== Modules

Javascript libraries and ready-to-use applications gets a website dynamic.
JS modules add complex functionality to your web pages for example image and 
video content. Or slider and lightboxes present image content animated as 
a show; best viewed by a lightbox.

== Slider

Slider and carousels can be used for a quite compact form of image galleries. 
This example show some pictures having individual caption text *and* support 
a lightbox to enlarge images full size. For the example below, a quite simple 
lightbox is used: *Lightbox V2*; or short: *lightbox*.

.Nice cats
carousel::owl_demo_cats[role="mb-5"]


== Galleries

To create *image* and *video* galleries, J1 Template implements the jQuery
plugin *JustifiedGallery* as the *main* gallery module. Beside Justified
Gallery, a gallery based on pure _Bootstrap_ code is available with the build-in
gallery app *gallery*.

*Justified Gallery* is a great jQuery plugin to create responsive, infinite
and high quality *justified* image galleries. J1 Template combines the gallery
with the *lightboxes* supported to *enlage* the images of a gallery.

.Masonry grid layout of Justified Gallery
carousel::jg_live_demo[role="mb-5"]


== Lightboxes

A *Lightbox* in general is a helper which displays enlarged, almost
screen-filling versions of pictures (or videos), while dimming the rest of the
page. The technique, introduced by Lightbox V2, gained widespread popularity
due to its simple and elegant style. The term *lightbox* is used since then for
Javascript libraries to support such functionality.

For J1 Template, two different lightboxes can be used:

* Lightbox V2 (lightbox)
* LightGallery

.A Lightbox block for grouped images
lightbox::example-group[ 400, {data-images-group}, group ]
