---
title:                                  J1 Template
tagline:                                become a patron
date:                                   2021-02-01 00:00:00
description: >
                                        Help to create premium content

tags:                                   [ Patron, Premium, Content ]
categories:                             [ pages ]

exclude_from_search:                    true

permalink:                              /pages/public/about/become_a_patron/
regenerate:                             false

resources:                              [ lightbox ]
resource_options:
  - attic:
      padding_top:                      400
      padding_bottom:                   50
      opacity:                          0.5
      slides:
        - url:                          /assets/images/modules/attics/premium-1920x1280-bw.jpg
          alt:                          Photo by Anders Nord on Unsplash
          badge:
            type:                       unsplash
            author:                     Anders Nord
            href:                       https://unsplash.com/@annoand/portfolio
---

// Page Initializer
// =============================================================================
// Enable the Liquid Preprocessor
:page-liquid:

// Set (local) page attributes here
// -----------------------------------------------------------------------------
// :page--attr:                         <attr-value>

//  Load Liquid procedures
// -----------------------------------------------------------------------------
{% capture load_attributes %}themes/{{site.template.name}}/procedures/global/attributes_loader.proc{%endcapture%}

// Load page attributes
// -----------------------------------------------------------------------------
{% include {{load_attributes}} scope="global" %}


// Page content
// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

// Include sub-documents
// -----------------------------------------------------------------------------

_Patron_ allows fans -- the *patrons* -- to pay creators for their work. Many
of these creators are influencers: photographers on Instagram, comedians
on YouTube, podcasters that tweet, creative technicians providing useful
software, tools and tutorials.

Simple like this.


== Become a Patron

What does that mean? A _Patron_ support a _Creator_ for the provided content
they love, they like to use: excellent content services -- created with passion.

What does a creator need to provide outstanding, useful products to the people?

No surprise: time and money. What is, vice versa, quite the same. But that's not
all.
