#collections:

  # ----------------------------------------------------------------------------
  # Site Settings
  #
  # - label:          Site Configuration
  #   name:           j1_site_config                                            # Used in routes, e.g., /admin/collections/blog 
  #   files:

      # ------------------------------------------------------------------------
      # 000 Simple List
      #
      - label: "Social Media"
        name: "social"
        file: "_data/modules/defaults/social_media.yml"
        fields:
          - label:  platform
            name:   platform
            widget: list
            fields:
              - {label: Name, name: name, widget: string}
              - {label: Icon, name: icon, widget: string}
              - {label: Link, name: link, widget: string}
