# ----------------------------------------------------------------------------
# Site Configuration
#
# - label: Site Configuration
#   name:  site_config                                                          # Used in routes, e.g., /admin/collections/blog
#   files:

    # ------------------------------------------------------------------------
    # VARIABLE LIST settings
    #
    - label: VARIABLE List
      name:  list_settings
      file:  packages/400_template_site/_cc_test_data/_data/blocks/001_variable_lists.yml
      fields:
        - label:      Home Section
          name:       sections
          widget:     list
          types:
            - label:  Carousel
              name:   carousel
              widget: object
              fields:
                - { label: Header, name: header, widget: string, default: "Image Gallery" }
                - { label: Template, name: template, widget: string, default: "carousel.html" }
                - label:  Images
                  name:   images
                  widget: list
                  field: {label: Image, name: image, widget: image}
            - label:    Spotlight
              name:     spotlight
              widget:   object
              fields:
                - { label: Header, name: header, widget: string, default: "Spotlight" }
                - { label: Template, name: template, widget: string, default: "spotlight.html" }
                - { label: Text, name: text, widget: text, default: "Hello World" }
