#collections:

  # ----------------------------------------------------------------------------
  # Module Default Settings
  #
  # - label:          Module Configuration
  #   name:           module_default_settings
  #   files:
  
      # ------------------------------------------------------------------------
      # J1 Navigation
      #
      - label:      J1 Navigation
        name:       config_navigation
        file:       _data/modules/defaults/navigator.yml
        fields:
          # --------------------------------------------------------------------
          # Global settings
          #
          - label:  Global settings
            name:   defaults
            hint:   Global configuration settings for J1 Navigation Module
            widget: object
            fields: 
  
              - { label: Icon Family, name: icon_family, widget: select, options: [ MDI, FA ], hint: Default Icon Family for the Navigation Module }
  
              # ----------------------------------------------------------------
              # Navigation Bar settings
              #
              - label:  Navigation Bar settings
                name:   nav_bar
                hint:   Controls the main navigation  bar
                widget: object
                fields:
                  - { label: navigation bar id, name: id, widget: string, hint: ID of the Navigation bar }
                  - { label: Media Breakpoint, name: media_breakpoint, widget: string, hint: Set the Media Breakpoint for the Navigation Bar get collapsed }
                  - { label: brand position, name: brand_position, widget: string, hint: Place the brand image }
                  - { label: brand type, name: brand_type, widget: select, options: [ image, text ], hint: Type of the brand image }
                  - { label: brand type collapsed, name: brand_type_collapsed, widget: select, options: [ image, text ], hint: Type of the brand image if the menu bar is collapsed }
                  - { label: fixed position, name: fixed, widget: boolean, hint: Defines the behaviour of the Menu bar if a page is scrolled }
                  - { label: style, name: style, widget: select, options: [ overlay, embedded ], hint: Set how the Navigation Bar integrates with the page header  }
                  - { label: color, name: color, widget: string, hint: TBD }
                  - { label: position, name: position, widget: select, options: [ left, center, right ], hint: Position of the menu bar }
                  - { label: bottom line size, name: bottom_line_height, widget: number, min: 0, max: 5, hint: Size of the line at the bottom of the navigation bar }
                  - { label: bottom line color, name: bottom_line_color, widget: string, hint: Color of the line at the bottom of the navigation bar }
                  - { label: background color expanded, name: background_color_full, widget: string, hint: Background color of the menu bar if expanded }
                  - { label: background color scrolled, name: background_color_scrolled, widget: string, hint: Background color of the menu bar if the page is scrolled }
                  - { label: background color collapsed, name: background_color_collapsed, widget: string, hint: Background color of the menu bar if collapsed }
  
  
              # ----------------------------------------------------------------
              # Navigation Menu settings
              #
              - label:  Menu Bar settings
                name:   nav_menu
                hint:   Controls the behaviour of the Navigation Menu
                widget: object
                fields:
                  - { label: menu id, name: id, widget: string, hint: ID of the menu bar container }
                  - { label: data path, name: data_path, widget: string, hint: HTML portion of the menu bar (loaded via AJAX) }
                  - { label: raised level, name: raised_level, widget: number, min: 0, max: 25, hint: TBD }
                  - { label: delay menu open, name: delay_menu_open, widget: number, min: 0, max: 500, hint: Delays a menu to open measured in milliseconds }
                  - { label: max lenght, name: max_height, number, min: 200, max: 1000, hint: Limits a menu for its lenght (y-axis) }
                  - { label: menu font size, name: menu_font_size, widget: string, hint: Size of the font used for menu entries }
                  - { label: megamenu font size, name: megamenu_font_size, widget: string, hint: Size of the font used for MEGA menu entries }
                  - { label: menu item color, name: menu_item_color, widget: string, hint: Menu item color }
                  - { label: menu item color selected, name: menu_item_color_hover, widget: string, hint: Menu item color if selected }
                  - { label: dropdown style, name: dropdown_style, widget: select, options: [ raised, flat ], hint: Dropdown menu style }
                  - { label: item style, name: dropdown_item_style, widget: select, options: [ raised, flat ], hint: Dropdown menu item style }
                  - { label: animate, name: dropdown_animate, widget: boolean, hint: Enables animation on dropdown menus }
                  - { label: animation on open, name: dropdown_animate_in, widget: string, hint: Animation if a dropdown menu is opened. See AnimateCSS for animation types }
                  - { label: animation on close, name: dropdown_animate_out, widget: string, hint: Animation if a dropdown menu is closed. See AnimateCSS for animation types }
                  - { label: animation duration, name: dropdown_animate_duration, widget: number, min: 0, max: 2000, hint: Duration an animation get finished. Duration is measured in milliseconds }
                  - { label: item width, name: dropdown_item_width, number, min: 200, max: 1000, hint: TBD }
                  - { label: menu height_max, name: dropdown_menu_height_max, widget: string, hint: TBD }
                  - { label: font size, name: dropdown_font_size, widget: string, hint: TBD }
                  - { label: padding x, name: dropdown_padding_x, widget: string, hint: TBD }
                  - { label: padding y, name: dropdown_padding_y, widget: string, hint: TBD }
                  - { label: item color, name: dropdown_item_color, widget: string, hint: TBD }
                  - { label: border color, name: dropdown_border_color, widget: string, hint: TBD }
                  - { label: border top, name: dropdown_border_top, widget: number, hint: TBD }
                  - { label: border radius, name: dropdown_border_radius, widget: string, hint: TBD }
                  - { label: background color hover, name: dropdown_background_color_hover, widget: string, hint: TBD }
                  - { label: background color active, name: dropdown_background_color_active, widget: string, hint: TBD }
  
  
              # ----------------------------------------------------------------
              # Navigation Quick Links settings
              #
              - label:  QuickLinks settings
                name:   nav_quicklinks
                hint:   Controls the behaviour of the Quick Links
                widget: object
                fields: 
                  - { label: enabled, name: enabled, widget: boolean, hint: Enables or Disables Quicklinks }
                  - { label: id, name: id, widget: string, hint: ID of the Quicklinks bar }
                  - { label: data path, name: data_path, widget: string, hint: HTML portion of Quicklinks (loaded via AJAX) }
                  - { label: icon family, name: icon_family, widget: select, options: [ MDI, FA ], hint: TBD }
                  - { label: icon color, name: icon_color, widget: string, hint: TBD }
                  - { label: item color selected, name: icon_color_hover, widget: string, hint: TBD }
                  - { label: item size, name: icon_size, widget: string, hint: TBD }
                  - { label: cookies icon, name: cookies_icon, widget: string, hint: TBD }
                  - { label: topsearch icon, name: top_search_icon, widget: string, hint: TBD }
                  - { label: sidebar, name: sidebar, widget: boolean, hint: TBD }
                  - { label: sidebar icon, name: sidebar_icon, widget: string, hint: TBD }
                  - { label: disqus icon, name: disqus_icon, widget: string, hint: TBD }
                  - { label: disqus url, name: disqus_url, widget: string, hint: TBD }
                  - { label: github icon, name: github_icon, widget: string, hint: TBD }
                  - { label: github url, name: github_url, widget: string, hint: TBD }
                  - { label: patreon icon, name: patreon_icon, widget: string, hint: TBD }
                  - { label: patreon url, name: patreon_url, widget: string, hint: TBD }
                  - { label: facebook icon, name: facebook_icon, widget: string, hint: TBD }
                  - { label: facebook url, name: facebook_url, widget: string, hint: TBD }
                  - { label: twitter icon, name: twitter_icon, widget: string, hint: TBD }
                  - { label: twitter url, name: twitter_url, widget: string, hint: TBD }
                  - { label: twitter url, name: twitter_url, widget: string, hint: TBD }
                  - { label: signin, name: signin, widget: boolean, hint: TBD }
                  - { label: signin client, name: signin_client, widget: select, options: [ enabled, disabled ], hint: TBD }
                  - { label: signin icon, name: signin_icon, widget: string, hint: TBD }
                  - { label: signout icon, name: signout_icon, widget: string, hint: TBD }
  
              # ----------------------------------------------------------------
              # Navigation Top Search settings
              #
              - label:  Topsearch settings
                name:   nav_topsearch
                hint:   Controls the behaviour of the Top Search
                widget: object
                fields: 
                  - { label: enabled, name: enabled, widget: boolean, hint: Enables or Disables Top Search }
                  - { label: id, name: id, widget: string, hint: ID of the Topsearch container }
                  - { label: type, name: type, widget: select, options: [ quicksearch, algolia, google ], hint: TBD }
                  - { label: icon family, name: icon_family, widget: select, options: [ MDI, FA ], hint: TBD }
                  - { label: icon color, name: icon_color, widget: string, hint: TBD }
                  - { label: icon size, name: icon_size, widget: string, hint: TBD }
                  - { label: search icon, name: search_icon, widget: string, hint: TBD }
                  - { label: close icon, name: close_icon, widget: string, hint: TBD }
                  - { label: input color, name: input_color, widget: string, hint: TBD }
                  - { label: background color, name: background_color, widget: string, hint: TBD }
                  - { label: placeholder, name: placeholder, widget: string, hint: TBD }
                  - { label: search heading lead, name: search_heading_lead, widget: string, hint: TBD }
                  - { label: result heading lead, name: result_heading_lead, widget: string, hint: TBD }
  
              # ----------------------------------------------------------------
              # Navigation Side Bar settings
              #
              - label:  Side Bar settings
                name:   nav_sidebar
                hint:   Controls the behaviour of the Side Bar
                widget: object
                fields: 
                  - { label: enabled, name: enabled, widget: boolean, hint: Enables or Disables the Side Bar }
                  - { label: id, name: id, widget: string, hint: ID of the Sidebar container }
                  - { label: data path, name: data_path, widget: string, hint: HTML portion of the Sidebar (loaded via AJAX) }
                  - { label: width, name: width, widget: number, min: 250, max: 500, hint: TBD }
                  - { label: icon family, name: icon_family, widget: select, options: [ MDI, FA ], hint: TBD }
                  - { label: icon color, name: icon_size, widget: string, hint: TBD }
                  - { label: icon size, name: id, widget: string, hint: TBD }
                  - { label: sidebar icon, name: sidebar_icon, widget: string, hint: TBD }
                  - { label: close icon, name: close_icon, widget: string, hint: TBD }
                  - { label: background color, name: background_color, widget: string, hint: TBD }
  
  
              # ----------------------------------------------------------------
              # Navigation Auth Client settings
              #
              - label:  Auth Client settings
                name:   nav_authclient
                hint:   Controls the behaviour of the Auth Client
                widget: object
                fields:
                  - { label: enabled, name: enabled, widget: boolean, hint: Enables or Disables the Auth Client }
                  - { label: id, name: id, widget: string, hint: ID of the Auth Client icon }
                  - { label: data path, name: data_path, widget: string, hint: HTML portion of Auth Client modals (loaded via AJAX) }
                  - { label: signin modal id, name: signin_modal_id, widget: string, hint: TBD }
                  - { label: authclient modals id, name: authclient_modals_id, widget: string, hint: TBD }
                  - { label: hide on cookies declined, name: hide_on_cookies_declined, widget: boolean, hint: TBD }
                  - { label: icon family, name: icon_family, widget: select, options: [ MDI, FA ], hint: TBD }
                  - { label: signin icon, name: signin_icon, widget: string, hint: TBD }
                  - { label: signout icon, name: signout_icon, widget: string, hint: TBD }
  


