// ~/document_base_folder/000_includes/documents/200_chapter/
// Chapter document: 200_chapter_document.asciidoc
// -----------------------------------------------------------------------------

== Chapter 2

link:https://en.wikipedia.org/wiki/Chapter_(books)[From Wikipedia]

In ancient civilizations, books were often in the form of papyrus or 
parchment scrolls, which contained about the same amount of text as a 
typical chapter in a modern book. This is the reason chapters in recent 
reproductions and translations of works of these periods are often presented 
as "Book 1", "Book 2" etc.

In the early printed era, long works were often published in multiple 
volumes, such as the Victorian triple decker novel, each divided into 
numerous chapters. Modern omnibus reprints will often retain the volume 
divisions. 

In some cases the chapters will be numbered consecutively all the way 
through, such that "Book 2" might begin with "Chapter 9", but in other 
cases the numbering might reset after each part (i.e., "Book 2, Chapter 1"). 
Even though the practice of dividing novels into separate volumes is rare 
in modern publishing, many authors still structure their works into 
"Books" or "Parts" and then subdivide them into chapters. 

A notable example of this is The Lord of the Rings which consists of 
six 'Books', each with a recognizable part of the story, although it 
is usually published in three volumes.


