---
title:                                  Site Search
tagline:                                Full-text search engine
description:                            Algolia Index for all documents

tags:                                   [
                                          Doc, Post, Documents, Full, Text,
                                          Site, Search, Engine, Algolia
                                        ]
index:                                  []
categories:                             [ pages ]

toc:                                    false

permalink:                              /pages/public/start/site_search/
regenerate:                             false

resources:                              [ algolia ]
resource_options:
  - masthead:
      opacity:                          0.2
      slides:
        - url:                          /assets/images/widescreen/featured-1920x800.webp
          alt:                          featured-1920x800 
---

// Enable the Liquid Preprocessor
// -----------------------------------------------------------------------------
:page-liquid:

// Set other global page attributes here
// -----------------------------------------------------------------------------

// Liquid procedures
// -----------------------------------------------------------------------------
//{% capture set_env_entry_document %}themes/{{site.template.name}}/procedures/global/set_env_entry_document.proc{%endcapture%}

// Initialize entry document paths
// -----------------------------------------------------------------------------
//{% include {{set_env_entry_document}} init_folders=all %}

// Load tags and urls
// -----------------------------------------------------------------------------
//include::{includedir}/attributes.asciidoc[tag=tags]
//include::{includedir}/attributes.asciidoc[tag=urls]
//include::{includedir}/attributes.asciidoc[tag=data]

// Additional Asciidoc page attributes goes here
// -----------------------------------------------------------------------------

// Include sub-documents
// -----------------------------------------------------------------------------

== Site Search

J1 Template integrates an Algolia Search Index for all documents of this site.
Using Algolia *Site Search*, looking for documents is done in a second.

++++
  <!-- See: https://community.algolia.com/instantsearch.js/v2/getting-started.html -->

  <!-- CurrentRefinedValues widget -->
  <div id="current-refined-values"></div>

  <!-- ClearAll widget -->
  <div id="clear-all"></div>

  <!-- SearchBox widget -->
  <div id="search-searchbar" class="mb-4"> </div>

  <!-- HitsPerPage widget -->
  <!-- div id="hits-per-page-selector"></div -->

  <div id="searcher" class"row">
    <div class="col-md-4 col-xs-6">
      <!-- CurrentRefinedValues widget -->
      <div id="current-refined-values"></div>
      <!-- RefinementList widget -->
      <div id="refinement-list" class="limit-y"></div>
    </div>

    <div class="col-md-8 col-xs-6">
      <!-- Pagination widget -->
      <div id="pagination"></div>
      <!-- Hits widget -->
      <ul class="list-unstyled">
        <div id="search-hits" class="result-list" >
          <div class="result-item"></div>
        </div>
      </ul>
    </div>

  </div>
++++

++++
<style>

#refinement-list {
  scrollbar-width: none; /* Firefox */
  -ms-overflow-style: none;  /* IE 10+ */
}

#refinement-list::-webkit-scrollbar {
  width: 0px; /* WebKit */
}

/*
input:focus{
  outline: none;
//  box-shadow: 0px 0px 5px #61C5FA;
  border: 1px solid #424242;
}

input:hover {
  border: 1px solid #424242;
  border-radius: 5px;
}

input:focus:hover{
  outline: none;
  box-shadow: 0px 0px 5px #424242;
  border: 1px solid #3f51b5;
  border-radius:0;
}
*/

.limit-y {
  max-height: 1000px;
  overflow-y: scroll;
}

.ais-pagination {
  -webkit-box-shadow: 0 !important;
  box-shadow: 0 !important;
  width: 100%;
}

.ais-pagination--item__active {
  background: #3f51b5;
}

.ais-clear-all--link, .ais-current-refined-values--clear-all,
.ais-price-ranges--button, .ais-range-input--submit {
  background: #3f51b5;
}


.ais-current-refined-values--link, .ais-geo-search--toggle-label,
.ais-hierarchical-menu--link, .ais-menu--link, .ais-price-ranges--link,
.ais-refinement-list--label, .ais-star-rating--link, .ais-toggle--label {
  color: #3f51b5;
}

.ais-refinement-list {
    margin-top: 1.25rem;
}

.search-result-item {
  margin-bottom: 0px;
}

.ais-search-box {
  max-width: 100%;
  /* margin-bottom: 15px; */
}

.ais-search-box--input {
  padding-left: 2.5rem !important;
}

.ais-search-box--magnifier {
  top: 1rem !important;
  right: 1rem !important;
  left: 1rem !important;
}

.ais-search-box--reset {
  top: 1rem !important;
  right: 1rem !important;
}

.ais-clear-all {
  margin-bottom: .125rem!important;
}

em.ais-Highlight {
  font-weight: bold;
  /* font-size: 1.125rem; */
  /* font-style: inherit; */
  color: #ef2929;
  font-style: unset !important;
}

</style>
++++
