---
title:                                  Floating SideBar
tagline:                                where to go
description:                            Where to go

tags:                                   [ Page, Roundtrip ]
index:                                  [ Start, Template, Whats, Up, Readme, TL;DR ]
categories:                             [ pages ]

permalink:                              /pages/public/learn/fsb/
regenerate:                             false

resources:                              [ lightbox ]
resource_options:
  - attic:
      padding_top:                      400
      padding_bottom:                   50
      opacity:                          0.5
      slides:
        - url:                          /assets/images/modules/attics/runner-1920x1200-bw.jpg
          alt:                          Photo by Alexander Redl on Unsplash
          badge:
            type:                       unsplash
            author:                     Alexander Redl
            href:                       https://unsplash.com/@alexanderredl
---

// Enable the Liquid Preprocessor
// -----------------------------------------------------------------------------
:page-liquid:


// Set other global page attributes here
// -----------------------------------------------------------------------------
//:my-asciidoc-attribute:

//  Load Liquid procedures
// -----------------------------------------------------------------------------
{% capture set_env_entry_document %}themes/{{site.template.name}}/procedures/global/set_env_entry_document.proc{%endcapture%}


// Initialize entry document environmental attributes
// -----------------------------------------------------------------------------
{% include {{set_env_entry_document}} %}

// Load tag, url and data attributes
// -----------------------------------------------------------------------------
// include::{includedir}/attributes.asciidoc[tag=tags]
// include::{includedir}/attributes.asciidoc[tag=urls]
// include::{includedir}/attributes.asciidoc[tag=data]

// Set local page attributes
// -----------------------------------------------------------------------------
// :images-dir:                         {imagesdir}/path/to/page/images


// Page content
// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

// Include sub-documents
// -----------------------------------------------------------------------------

++++
<div class="sidebar">
  <div class="floating-div">
    <p>This "floating div" could be a form, a call to action, an ad,
      or whatever other content you want to float in sidebar as the user
      scrolls up and down the page.
    </p>
  </div>
</div>
++++

Welcome to the pages of J1 Template. If your here first time,
hopefully you get on that page first. For sure, there is no better
place to step in.

Having a menu system is great. We hope the the navigator module of J1 will
support you to explore this site, find what your are looking for. The site
of J1 has grown over the last month a lot. Many documents were seeking for
a home. And we have really a bunch of them.

To get better orientated, the site is organized for *natural reading*. As we
use the English language for our international vistors (we are German),
*natural reading* means for a western language, reading from the left to the
right (LTR), and from top to down a page. The same to all menus, sections
and pages.

To read the site it is recommended to go for LTR. Other languages, other
countries and cultures go for RTL, but currently we've *no* support for RTL
implemented.

For that reason, it was a good decision to start from here.

== Whats up

First of all, you've started already! The important first step in to find
your way to Jekyll is done. Congratiulations.

The *Learn* section contains all you need to learn what Jekyll and J1 can do
for your website. For your new static web - if you like.

With this section you'll find a:

. *Roundtrip* to show some of the main features of the template system
  *J1*.

. *Kickstarter* are Tutorials. The most important one to start is *Web in a Day*.
  This tutorial guides you through all the steps to build a website using
  the template system Jekyll One - your site using Jekyll and the template J1.

== Where to go

You should go for the *Roundtrip* first. See what you will get. As an overview
of some of the main features of *J1*. The roundtrip is a *visual* tour. No
technical stuff, nothing academic.

Let's go more deeper and make things real - and your hands dirty. We
recomment to work on the Kickstarter *Web in a Day*. A nice one-day journey
diving into the world of Jekyll. You'll learn a lot and at the end of that day
you know what Jekyll, static webs and the template system J1 is all about.

You're welcome!

If you like, continue by walking through the roundtrip examples
link:/pages/public/learn/roundtrip/present_images/[by starting the tour here].

++++
<style>

  .sidebar {
    width:33.33%;
    float:left;
    padding: 0 10px;
  }

  .floating-div {
    background-color: #333;
    padding: 10px 50px;
    color:#EEE;
    font-size: 20px;
    margin-top:10px;
    position: absolute;
    right: -40px;
  }

  .sticky {
    position: fixed;
    top: 150px;
    right:-40px;
    margin: 0;
    width:calc(33.33% - 25px);
  }

  .abs {
    position: absolute;
    bottom: 10px;
    right:10px;
    width:calc(33.33% - 20px);
  }
</style>

<script>
  $(document).ready(function() {
    var dependencies_met_core = setInterval(function() {
      if (j1.getState() == 'finished') {
        // variables
        var main_content      = $('.js-toc-content');
        var m                 = $(main_content).offset().top;
        var topPosition       = $('.floating-div').offset().top - 10;
        var floatingDivHeight = $('.floating-div').outerHeight();
        var footer            = $('#j1_footer');
        var footerFromTop     = $('#j1_footer').offset().top;
        var absPosition       = footerFromTop - floatingDivHeight - 20;
        var win               = $(window);
        var floatingDiv       = $('.floating-div');

        win.scroll(function() {
          if (window.matchMedia('(min-width: 768px)').matches) {
            if ((win.scrollTop() > topPosition) && (win.scrollTop() < absPosition)) {
              floatingDiv.addClass('sticky');
              floatingDiv.removeClass('abs');

            } else if ((win.scrollTop() > topPosition) && (win.scrollTop() > absPosition)) {
              floatingDiv.removeClass('sticky');
              floatingDiv.addClass('abs');

            } else {
              floatingDiv.removeClass('sticky');
              floatingDiv.removeClass('abs');
            }
          }
        });
        clearInterval(dependencies_met_core);
      }
    }, 25);
  });
</script>
++++
