---
title:                                  J1 Publish
tagline:                                about
date:                                   2021-02-01 00:00:00
description: >
                                        This site support all people having one thing on
                                        their minds: bringing a web online. People quite
                                        often ask where to place a static site on the Internet.
                                        Is it possible for free?

tags:                                   [ Overview ]
categories:                             [ Software, Platforms, Contributers ]

scrollbar:                              false
comments:                               true
fam_menu_id:                            page_ctrl_simple

permalink:                              /pages/public/about/site/
regenerate:                             false

resources:                              [ lightbox ]
resource_options:
  - attic:
      padding_top:                      400
      padding_bottom:                   50
      opacity:                          0.5
      slides:
        - url:                          /assets/images/modules/attics/nicola-styles-1920x1280.jpg
          alt:                          Photo by Nicola Styles on Unsplash
          badge:
            type:                       unsplash
            author:                     Nicola Styles
            href:                       https://unsplash.com/@nicolastyles
---

// Page Initializer
// =============================================================================
// Enable the Liquid Preprocessor
:page-liquid:

// Set (local) page attributes here
// -----------------------------------------------------------------------------
// :page--attr:                         <attr-value>
:badges-enabled:                        true

//  Load Liquid procedures
// -----------------------------------------------------------------------------
{% capture load_attributes %}themes/{{site.template.name}}/procedures/global/attributes_loader.proc{%endcapture%}

// Load page attributes
// -----------------------------------------------------------------------------
{% include {{load_attributes}} scope="global" %}


// Page content
// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

ifeval::[{badges-enabled} == true]
{badge-j1--license} {badge-j1--version-latest} {badge-j1-gh--last-commit} {badge-j1--downloads}
endif::[]

// Include sub-documents
// -----------------------------------------------------------------------------

== About this site

This site support all people having one thing on their minds: *bringing a web
online*. People quite often ask where to place a static site on the Internet.
Is it possible for free?

These pages provide some example, some great options to publish your web.
And good news: all the pages are hosted for free.

[NOTE]
====
*Web* publishing, or *online* publishing, is the process of publishing content
on the Internet. It includes creating and uploading websites, updating webpages,
and posting blogs online. The published content may include text, images,
videos, and other types of media.
====

This site highlights top providers to deploy, to place your static web on the
Internet. Find more information on:

* what providers having *free* plans for publishing
  link:/pages/public/publishing/provider/[a website] on the Internet.
* how to link:/pages/public/publishing/publish/[pubslish a site] for
  selected providers.

Have fun!

== Features

J1 Template is a *gem-based* website template to be used with the static site
generator _Jekyll_. The Template System cannot operate on its own. A Ruby
development environment is needed to run J1. The easiest way to learn how J1
works to create a website is the tutorial
{url-j1-web-in-a-day--meet-and-greet}[Web in a Day, {browser-window--new}].

If you're an experienced user of _Jekyll_, the latest version is available at
{url-j1--download}[RubyGems, {browser-window--new}].

=== General

* Jekyll 4.2 support
* Ruby 2.7 support
* Asciidoc (Asciidoctor) and Markdown support
* Asciidoctor plugins included
* Bootstrap V4 (v4.6)
* Responsive Design
* Material Design
* Responsive Text
* Responsive HTML tables
* Compressed HTML, CSS and Javascript support
* Themes support (Bootswatch)
* Icon Font support (MDI, FA, Iconify, Twitter Emoji)
* Themeable source code highlighting (Rouge)
* Desktop and Mobile Web and Navigation ready
* Fully configurable
* 100/100/100 Google Lighthouse scores (performance depends on the webbrowser)

=== Modules and Extensions

* Bootstrap extensions included
* Asciidoctor extensions included
* Smooth-scoll support
* Full-text search engine included (Lunr)
* Blog Post navigation included
* Cookie Consent module (GDPR compatible) included
* Clipboard module included
* Floating Action Buttons included
* Navigation modules included
* Lightbox modules included
* Gallery modules included
* Carousel module included
* Video modules included

=== Addons and Integrations

* Featured example content included
* Royalty free images included
* Disqus support
* Google Analytics support (includes OptIn/OptOut support)
* Deploy to Github Pages, Netlify and Heroku ready

== Leave a comment
