---
title:                                  J1 Publish
tagline:                                about
date:                                   2021-02-01 00:00:00
description: >
                                        This site support all people having one thing on
                                        their minds: bringing a web online. People quite
                                        often ask where to place a static site on the Internet.
                                        Is it possible for free?

tags:                                   [ Overview ]
categories:                             [ Software, Platforms, Contributers ]

scrollbar:                              false

permalink:                              /pages/public/about/site/
regenerate:                             false

resources:                              [ lightbox ]
resource_options:
  - attic:
      padding_top:                      400
      padding_bottom:                   50
      opacity:                          0.5
      slides:
        - url:                          /assets/images/modules/attics/nicola-styles-1920x1280.jpg
          alt:                          Photo by Nicola Styles on Unsplash
          badge:
            type:                       unsplash
            author:                     Nicola Styles
            href:                       https://unsplash.com/@nicolastyles
---

// Page Initializer
// =============================================================================
// Enable the Liquid Preprocessor
:page-liquid:

// Set (local) page attributes here
// -----------------------------------------------------------------------------
// :page--attr:                         <attr-value>
:badges-enabled:                        true

//  Load Liquid procedures
// -----------------------------------------------------------------------------
{% capture load_attributes %}themes/{{site.template.name}}/procedures/global/attributes_loader.proc{%endcapture%}

// Load page attributes
// -----------------------------------------------------------------------------
{% include {{load_attributes}} scope="global" %}


// Page content
// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

ifeval::[{badges-enabled} == true]
{badge-j1--license} {badge-j1--version-latest} {badge-j1-gh--last-commit} {badge-j1--downloads}
endif::[]

// Include sub-documents
// -----------------------------------------------------------------------------

== About this site

This site support all people having one thing on their minds: *bringing a web
online*. People quite often ask where to place a static site on the Internet.
Is it possible for free?

These pages provide some example, some great options to publish your web.
And good news: all the pages are hosted for free.

[NOTE]
====
*Web* publishing, or *online* publishing, is the process of publishing content
on the Internet. It includes creating and uploading websites, updating webpages,
and posting blogs online. The published content may include text, images,
videos, and other types of media.
====

This site highlights top providers to deploy, to place your static web on the
Internet. Find more information on:

* what providers having *free* plans for publishing
  link:/pages/public/publishing/provider/[a website] on the Internet.
* how to link:/pages/public/publishing/publish/[pubslish a site] for
  selected providers.

Have fun!
