# ------------------------------------------------------------------------------
# ~/_data/j1_config.yml
# J1 Template global settings
#
# Product/Info:
# https://jekyll.one
#
# Copyright (C) 2021 Juergen Adams
#
# J1 Template is licensed under the MIT License.
# For details, see https://jekyll.one
# ------------------------------------------------------------------------------

# ==============================================================================
# URL configuration
#
# ------------------------------------------------------------------------------
#
# All links will be name-spaced by base_path if defined.
# Links in your website should always be prefixed with {{base_path}}
# however this value will be dynamically changed depending on your
# deployment situation.
#
# CNAME (http://yourcustomdomain.com)
#   DO NOT SET base_path
#   (url's will be prefixed with "/" and work relatively)
#
# GitHub Pages (http://username.github.io)
#   DO NOT SET base_path
#   (url's will be prefixed with "/" and work relatively)
#
# GitHub Project Pages (http://username.github.io/project-name)
#
#   A GitHub Project site exists in the `gh-pages` branch of one of
#   your repositories.
#  REQUIRED! Set base_path to: http://username.github.io/project-name
#
# CAUTION:
#   - When in localhost, your site will run from root "/" regardless
#     of base_path
#   - Only the following values are falsy: ["", null, false]
#   - When setting base_path it must be a valid url.
#     This means always setting the protocol (http|https) or
#     prefixing with "/"
#
#base_path:

# By default, the asset_path is automatically defined relative to
# base_path plus the enabled theme, e.g
#
#     [base_path]/assets/themes/[THEME-NAME]
#
#     e.g. /assets/themes/bootstrap
#
# Override this by defining an absolute path to assets here.
# ex:
#   http://s3.amazonaws.com/yoursite/themes/watermelon/assets
#
asset_path:                             /assets/themes/j1
app_path:                               /assets/apps
image_path:                             /assets/images

# These paths are to the main pages J1 ships with.
# Some template helpers refer to these paths
#
#pages_path:                            /builder/pages
archive_path:                           /builder/posts/timeline
categories_path:                        /builder/categories
tags_path:                              /builder/tags
#atom_path:                             /atom.xml
#rss_path:                              /rss.xml


# -------------------------------------------------------------------------
# Common site URLs
#
about-site-url:                         /pages/public/about/site/
user_info_url:                          /pages/public/legal/en/privacy/
theme_author_url:                       https://jekyll.one


# ==============================================================================
# DATA path configuration settings
#
# ------------------------------------------------------------------------------
message_catalog_data_path:              /assets/data/messages.yml
colors_data_path:                       /assets/data/colors.json
font_size_data_path:                    /assets/data/font_sizes.json
country_data_path:                      /assets/data/countries.json


# ==============================================================================
# PAGE configuration settings
#
# ------------------------------------------------------------------------------

# ------------------------------------------------------------------------------
#   flicker_timeout
#   ----------------------------------------------------------------------------
#   Number of milliseconds (ms) the current page is hidden (display: none)
#   to prevent "DOM flicker" (aka "FOUC": Flash of unstyled content)
#
#   prettify
#   ----------------------------------------------------------------------------
#   If set to true, all generated HTML pages (by Liquid|Jekyll) get 
#   formatted "pretty" by layout "default".
#
#   NOTE: Used for developent mode ONLY
#   NOTE: See ~/packages/300_template_src/_layouts/default.html
#
# ------------------------------------------------------------------------------
flicker_timeout:                        150

# -------------------------------------------------------------------------
# HTML Pretty Print
#
prettify:                               true


# ==============================================================================
# USER configuration settings
#
# ------------------------------------------------------------------------------

# -------------------------------------------------------------------------
# Default settings
#
user:
  provider:                             site
  provider_url:                         https://jekyll.one
  user_name:                            vistor
  status:                               active
  provider_membership:                  guest
  provider_permissions:                 public

# ==============================================================================
# FRAMEWORK configuration settings
#
# ------------------------------------------------------------------------------
#
# -------------------------------------------------------------------------
# BOOTSTRAP framework settings
#
bootstrap:
  tooltips:                             true
  popovers:                             true
  default_theme:                        uno

# -------------------------------------------------------------------------
# Font AweSome settings
#
fa:
  color:                                default

# -------------------------------------------------------------------------
# Body style settings
#
body:
  scrollbar:                            true                                    # false
  background-color:                     md_gray_50
  font-color:                           md_gray_900   # default
  font-size:                            1em
  font-weight:                          400
  line-height:                          1.5


# ==============================================================================
# CONNECTOR configuration settings
#
# ------------------------------------------------------------------------------

# ------------------------------------------------------------------------------
# COMMENTS connector settings
#
# Set 'enabled' to false to turn commenting off globally
# Set 'provider' to the comment provider you want to use
# ------------------------------------------------------------------------------
# disqus
#
#   short_name: your-disqus-short-name (w/o disqus.com)
#
# ------------------------------------------------------------------------------
comments:
  enabled:                              true
  provider:                             disqus
  disqus:    
    short_name:                         jekyll-one
# facebook:
#   appid:                              123
#   num_posts:                          5
#   width:                              580
#   colorscheme:                        light
# custom:    
#   custom_data:

# -------------------------------------------------------------------------
# ANALYTICS connector settings
#
# Set 'enabled' to false to turn analytics off globally
# Set 'provider' to the analytics provider you want to use
#
analytics:
  enabled:                              true
  provider:                             google
  google:
    tracking_id:                        'UA-138160879-1'
  custom:    
    custom_data:

# -------------------------------------------------------------------------
# ADVERTISING connector settings
#
# Set 'enabled' to false to turn advertising off globally
# Set 'provider' to the analytics provider you want to use
#
advertising:
  enabled:                              true
  provider:                             google
  google:    
    publisher_id:                       ca-pub-6537273267695855
  custom:    
    custom_data:

# -------------------------------------------------------------------------
# SHARING connector settings (currently NOT supported)
#
# Settings for sharing helper. Sharing is for things like tweet, plusone,
# like, reddit buttons etc. Set 'provider' to the sharing provider you
# want to use. Set 'provider' to false to turn sharing off globally.
#
# Set 'enabled' to false to turn sharing off globally
# Set 'provider' to the sharing provider you want to use
#
# sharing:
#   enabled:                            false
#   provider:


# ==============================================================================
# Typography configuration settings
#
# ------------------------------------------------------------------------------
typography:
  rtext:                                true
  rtext_size:                           300

# ==============================================================================
# SASS and CSS configuration settings
#
# ------------------------------------------------------------------------------
#
custom_theme:
  custom_scss:                          false
  custom_css:                           false


# ------------------------------------------------------------------------------
# END config