---
# ~/document_base_folder
# Master Document HTML conversion:      document_title.adoc
#
title:                                  Asciidoc Skeleton
tagline:                                base file and folder structure
description:

category:                               examples
tags:                                   [ Asciidoc, Example ]
index:                                  [ Document, Skeleton, Folder, Structure ]

resources:                              [ lightbox ]
permalink:                              /pages/public/learn/kickstarter/web_in_a_day/document/skeleton/
regenerate:                             false

resource_options:
  - toccer:
      collapseDepth:                    3

  - attic:
      padding_top:                      400
      padding_bottom:                   50
      opacity:                          0.5 
      slides:
        - url:                          /assets/images/modules/attics/library-1920x1280-bw.jpg
          alt:                          library-1920x1280-bw
---

// Set global page attributes
// -------------------------------------------------------------------
:page-liquid:

// ~/document_base_folder
// AsciiDoc Master Document: document_title.adoc
// -------------------------------------------------------------------


//  Load Liquid procedures
// -------------------------------------------------------------------
{% capture set_env_entry_document %}themes/{{site.template.name}}/procedures/global/set_env_entry_document.proc{%endcapture%}

// Initialize entry document environmental attributes
// -------------------------------------------------------------------
{% include {{set_env_entry_document}} init_folders=all %}

// Load tag, url and data attributes
// -------------------------------------------------------------------
include::{includedir}/attributes.asciidoc[tag=tags]
include::{includedir}/attributes.asciidoc[tag=urls]
include::{includedir}/attributes.asciidoc[tag=data]

// Set local page attributes
// -------------------------------------------------------------------
:doctype:                               book
:toc-enabled:                           false

// MAIN
// =============================================================================

// Document Header
// -------------------------------------------------------------------
= Asciidoc Writer's Guide

ifdef::toc-enabled[]
:toc: left
:toclevels: 4
endif::[]


// Page content
// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

[.lead]
The *Asciidoc Document Skeleton* a helper for setting up a base file and
folder structure for *multi-chapter* AsciiDoc projects based on _Jekyll_
and _J1 Template_. You need *both* to use this skeleton creating AsciiDoc
documents from it.

[NOTE]
====
.Converting the Skeleton

The Asciidoc Document Skeleton is fully *relocateable* and can be placed in
any subfolder of your Jekyll site for *HTML* output. For *PDF* output. A
single variable `BASE_PATH` has to be set for your environment.

See the batch helper files `a2p.bat` for _Windows_ or `a2p.sh` for the shell
script used on _Unix_ or _Linux_ OS (bash).
====

The skeleton can be used to create HTML output (backend *html5*) and PDF
output (backend *pdf*) as well. _J1 Template_ comes with the full support
of _Asciidoctor PDF_, a Ruby-based implementation for _Asciidoctor_ based on
the PDF converter _Prawn_.

[role="mb-5"]
*Happy Jekylling!*

// Include Intro
// -------------------------------------------------------------------

include::{documentsdir}/000_intro.asciidoc[]


// Include Sublevel Entry Documents
// -------------------------------------------------------------------

include::{documentsdir}/100_chapter.asciidoc[]

include::{documentsdir}/200_chapter.asciidoc[]


// Document References
// -------------------------------------------------------------------

include::{documentsdir}/900_sources.asciidoc[]
