=== OmniLogin

Add `.modal-dialog-centered` to `.modal-dialog` to vertically center the modal.

++++
<div class="ml-2 mb-5">
  <!-- Button trigger modal -->
  <button type="button" class="btn btn-primary btn-raised" data-toggle="modal" data-target="#modalOmniLogin">
    OmniLogin
  </button>
</div>

<!--Modal OmniLogin -->
<div class="modal fade show" id="modalOmniLogin" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" data-backdrop="false">
  <div class="modal-dialog modal-notify modal-lg modal-notify modal-info" role="document">
    <!-- Content -->
    <div class="modal-content">
      <!--Header-->
      <div class="modal-header">
        <p class="lead">Cookie Consent</p>
      </div>
      <!-- Body -->
      <div class="modal-body">
        <div class="px-3">
          <p class="pt-1 pr-2">
            This website uses cookies to ensure you get the best experience on our content,
            presented user-friendly, more effective and safer.
          </p>
        </div>
        <div class="px-3">
          
          <h6 class="card-subtitle text-muted mt-4 mb-2">Cookie usage</h6><table class="tableblock frame-all grid-all stretch table-responsive mr-2">
            <colgroup>
              <col style="width: 10%;">
              <col style="width: 10%;">
              <col style="width: 10%;">
              <col style="width: 10%;">
              <col style="width: 60%;">
            </colgroup>
            <thead>
              <tr>
                <th class="tableblock halign-center valign-top">Session Cookies</th>
                <th class="tableblock halign-center valign-top">Persistent Cookies</th>
                <th class="tableblock halign-center valign-top">First-party Cookies</th>
                <th class="tableblock halign-center valign-top">Second-party Cookies</th>
                <th class="tableblock halign-left valign-top">Description</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td class="tableblock halign-center valign-top">
                  <p class="tableblock"><span class="icon red"><i class="fa fa-check"></i></span></p>
                </td>
                <td class="tableblock halign-center valign-top">
                  <p class="tableblock"><span class="icon green"><i class="fa fa-check"></i></span></p>
                </td>
                <td class="tableblock halign-center valign-top">
                  <p class="tableblock"><span class="icon green"><i class="fa fa-times"></i></span></p>
                </td>
                <td class="tableblock halign-center valign-top">
                  <p class="tableblock"><span class="icon green"><i class="fa fa-times"></i></span></p>
                </td>
                <td class="tableblock halign-left valign-top">
                  <div class="content">
                    <div class="paragraph">
                      <p>May used in sections marked by <span class="icon green"><i class="fa fa-check"></i></span></p>
                    </div>
                  </div>
                </td>
              </tr>
            </tbody>
          </table>
        </div>
        <!-- Footer -->
        <div class="modal-footer justify-content-right mt-5">
          <a type="button" id="cookiePolicy" class="btn btn-secondary-modal mr-2" data-dismiss="modal">
            <i class="mdi mdi-18px mdi-dark mdi-read"></i>
            Cookie Policy
          </a>
          <a type="button" id="acceptButton" class="btn btn-primary-modal mr-2" data-dismiss="modal">
            <i class="mdi mdi-18px mdi-dark mdi-check"></i>
            Yes, I accept cookies
          </a>
          <a type="button" id="declineButton" class="btn btn-outline-modal mr-2" data-dismiss="modal">
            <i class="mdi mdi-18px mdi-dark mdi-close"></i>
            No, I refuse cookies
          </a>
        </div> <!-- END Footer -->
      </div> <!-- END Body -->
    </div> <!-- END Content -->
  </div>
</div>
<!-- END Modal OmniLogin -->
<script>
  var signIn = {
    provider:   'Github',
    login:      false
  };
  $('ul.nav-pills > li').click(function (e) {
      e.preventDefault();
      signIn.provider = $(this).text().trim();
      signIn.provider = signIn.provider.toLowerCase();
  });
  $("button").click(function() {
    if (this.id === "loginButton") {
      signIn.login = true;
    } else {
      signIn.login = false;
    }
  });
  $("#modalOmniLogin").on('hidden.bs.modal', function() {
    if (signIn.login == true) {
      console.log(signIn.provider, ' : ', signIn.login);
      var provider = signIn.provider.toLowerCase();
      var link = '/auth?provider=' + provider;
      window.location.href = link;
    } else {
      console.log(signIn.provider, ' : ', signIn.login);
    }
  });
</script>
++++
