---
layout:                                 page
scrollbar:                              false

title:                                  J1 Control Center
tagline:                                Manage Your Site
description:                            A CMS environment based on Netlify CMS

tags:                                   [ AdminCMS, CMS, Netlify, Site, Manager ]
index:                                  []
categories:                             [ apps ]

toc:                                    false
permalink:                              /apps/protected/netlify-cms/page/
regenerate:                             false

resources:                              [ iFramer ]
resource_options:
---

// Enable the Liquid Preprocessor
// -----------------------------------------------------------------------------

// Set other global page attributes here
// -----------------------------------------------------------------------------

// Liquid procedures
// -----------------------------------------------------------------------------

// Initialize entry document paths
// -----------------------------------------------------------------------------

// Load tags and urls
// -----------------------------------------------------------------------------

// Additional Asciidoc page attributes goes here
// -----------------------------------------------------------------------------

// Include documents
// -----------------------------------------------------------------------------

ifdef::cc-preface[]
*J1 Control Center* is based on _Netlify CMS_, an open source content management
system (CMS) for *static* websites: managed by _Netlify_. It provides a 
friendly user interface (UI) system to manage websites, stored in a Git 
repository.

You can use *J1 Control Center* for all sites based on _J1 Template_ to create 
faster, more flexible web projects. Content is stored in a Git repository 
alongside your code for easier versioning, multi-channel publishing, and the 
option to handle sites content updates directly in Git.

[NOTE, role="mb-4"]
====
No matter where you *access* J1 Control Center -- whether running locally, in a 
staging environment, or in your published site -- it will always fetch 
and commit files in your hosted *repository* (GitHub), on the *branch* you 
configured with your J1 Admin CMS configuration (`~/admin/config/config.yml`). 

Keep in mind, that content fetched in the UI will match the content in the 
*repository*, which may be *different* from your *locally* running *site*.
This means that content *saved* using the UI will save directly to the 
hosted *repository*, even if you're running the J1 Admin CMS locally or 
in staging.
====
endif::[]

/////
== GitHub Auth Demo

++++
  <!-- Make sure to include Nelify's authentiation library -->
  <!-- Also available via npm as netlify-auth-providers -->
  <script src="https://unpkg.com/netlify-auth-providers"></script>

  <script>
    $(function() {
      $("#login").on("click", function(e) {
        e.preventDefault();
        // var authenticator = new netlify.default ({});
        // var authenticator = new netlify.configure({site_id: "bbcd1b70-a958-4eee-92cb-1f15247f699c"});
        var authenticator = new netlify.default({site_id: "bbcd1b70-a958-4eee-92cb-1f15247f699c"});
        authenticator.authenticate({provider:"github", scope: "user"}, function(err, data) {
          if (err) {
            return $("#output").text("Error Authenticating with GitHub: " + err);
          }
          $("#output").text("Authenticated with GitHub. Access Token: " + data.token);
        });
      });
    });
  </script>

  <p><a href="#" id="login">Authenticate</a></p>
  <p id="output"></p>
++++
/////


// == Control Center
++++
<div id="cms-manager" class="row mt-3">
  <iframe
    src="/apps/protected/netlify-admin/page/"
    style="border-width:0; width:100%; height:1024px">
  </iframe>
</div>
++++

