---
title:                                  Mobile Menu
tagline:                                documentation
description:                            Mobile Menu Documentation

tags:                                   [ App, Doc, Menu, Mobile ]
index:                                  [ Mobile, Menu, Light ]
categories:                             [ app ]

toc:                                    true
scrollbar:                              false

permalink:                              /pages/public/mmenu/man/
regenerate:                             false

resources:                              []
resource_options:
  - attic:
      padding_top:                      400
      padding_bottom:                   50
      opacity:                          0.5
      slides:
        - url:                          /assets/images/modules/attics/admin-dashboard-bootstrap-1280x600.png
          alt:                          Admin Dashboard
---
// Enable the Liquid Preprocessor
// -----------------------------------------------------------------------------
:page-liquid:

// Set other global page attributes here
// -----------------------------------------------------------------------------
//:my-asciidoc-attribute:

//  Load Liquid procedures
// -----------------------------------------------------------------------------
{% capture set_env_entry_document %}themes/{{site.template.name}}/procedures/global/set_env_entry_document.proc{%endcapture%}

// Initialize entry document environmental attributes
// -----------------------------------------------------------------------------
{% include {{set_env_entry_document}} %}

// Load tag, url and data attributes
// -----------------------------------------------------------------------------
include::{includedir}/attributes.asciidoc[tag=tags]
include::{includedir}/attributes.asciidoc[tag=urls]
include::{includedir}/attributes.asciidoc[tag=data]

// Set local page attributes
// -----------------------------------------------------------------------------
:images-dir:                            {imagesdir}/pages/roundtrip/100_present_images


// Page content
// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

// Include sub-documents
// -----------------------------------------------------------------------------

*Mmenu* (short for mobile menu) is a JavaScript plugin for creating app
look-alike off-canvas menus. It turns a basic HTML menu structure
(with `<nav>`, `<ul>`, `<li>` and `<a>` or `<span>` elements) into a
fully functional off-canvas menu with sliding submenus.

The mmenu.js plugin knows its way around a bit more complex HTML structures
as well, so you probably don't need to change any markup if your migrating
from another script or plugin.


## Getting started

This documentation page assumes you have some knowledge of HTML, CSS and
JavaScript. If you are totally new to frontend development, it might not
be the best idea to jump right into a framework as your first step -
grasp the basics then come back!

[NOTE]
====
If you're new to using the mmenu light plugin, please
link:{mmenu-home}[grab a copy] of the mmenu light plugin and try
link:{mmenu-tut}[the tutorial].
====

After the plugin is invoked, there are two add-ons available for the
menu: `navigation` and `offcanvas`.

`navigation()`::
  Creates the navigation with a fixed navbar and sliding submenus from
  `<nav />`, `<ul />`, `<li />` and `<a />` (or `<span />`) elements.
`offcanvas()`::
  Creates an off-canvas drawer. This drawer can be populated with any
  kind of content.

Note that both add-ons have their own set of options, CSS variables and
API methods.

## Options

The mmenu light plugin and both the `navigation` and `offcanvas` add-ons
provide a set of options for customizing your menu. The default values
can be overridden by passing new values to the method.

[source, html]
----
<script>
    document.addEventListener(
        "DOMContentLoaded", () => {
            const menu = new MmenuLight(
                document.querySelector( "#my-menu" ),
                "(max-width: 600px)"
            );

            const navigator = menu.navigation({
                // options
            });

            const drawer = menu.offcanvas({
                // options
            });
        }
    );
</script>
----

### Mmenu Plugin

Option

Datatype

Default value

Description

node

_HTMLElement_

`null`

The HTML element you want to turn in an off-canvas menu.

mediaQuery

_String_

`"all"`

MediaQuery for when the menu should be enabled.

### Navigation add-on

Option

Datatype

Default value

Description

\{

selected

_String_

`"Selected"`

Classname to use for finding the selected `<li />`.

slidingSubmenus

_Boolean_

`true`

Wether or not to use sliding submenus (forced to be `false` in IE11).

title

_String_

`"Menu"`

The title above the main panel. +
 For subpanels the text in its parent menu item is used.

theme

_String_

`"light"`

Color scheme to use. Possible values: `"light"` or `"dark"`

}

### Offcanvas add-on

Option

Datatype

Default value

Description

\{

position

_String_

`"left"`

The position for the menu. Possible values: `"left"` or `"right"`

}

## Styling (CSS)

It's pretty easy change the styling for the mmenu light plugin, just
override some of the CSS values and variables.

[source, css]
----
<style>
    .mm {
        background: #ffe;
        color: #330;
        --mm-spn-item-height: 46px;
        --mm-ocd-max-width: 500px;
    }
</style>
----

### Navigation add-on

It's pretty easy change the styling for the mmenu light plugin, just override
some of the CSS values and variables.

Variables

Datatype

Default value

Description

Values

background-color

_Color_

`#f3f3f3`

Background-color for the menu.

color

_Color_

`#444`

Color for the text and borders in the menu.

Variables

--mm-spn-item-height

_CSS value_

`50px`

Height for menu items.

--mm-spn-item-indent

_CSS value_

`20px`

Indent for menu items.

--mm-spn-line-height

_CSS value_

`24px`

Line-height for text in the menu.

### Offcanvas add-on

It's pretty easy change the styling for the mmenu light plugin, just override
some of the CSS values and variables.

Variables

Datatype

Default value

Description

Values

top

_CSS value_

`0`

Position relative to the top of the page.

bottom

_CSS value_

`0`

Position relative to the bottom of the page.

Variables

--mm-ocd-width

_CSS value_

`80%`

Width for the menu.

--mm-ocd-min-width

_CSS value_

`200px`

Minimal width for the menu.

--mm-ocd-max-width

_CSS value_

`440px`

Maximum width for the menu.

## API

After invoking the add-ons, an API is available for each add-on. With
this API, you can invoke the add-on methods to control the plugin
manually.

[source, html]
----
<script>
    document.addEventListener(
        "DOMContentLoaded", () => {
            const menu = new MmenuLight(
                document.querySelector( "#my-menu" )
            );

            const navigator = menu.navigation();
            const drawer = menu.offcanvas();

            navigator.openPanel(
                document.querySelector( "#my-ul" );
            );

            document.querySelector( 'a[href="#my-menu"]' )
                .addEventListener( 'click', ( evnt ) => {
                    evnt.preventDefault();
                    drawer.open();
                });
        }
    );
</script>
----

### Navigation add-on

Creates the navigation with a fixed navbar and sliding submenus from
`<nav>`, `<ul>`, `<li>` and `<a>` or `<span>` elements elements.

Method( arguments )

Datatype

Default value

Description

openPanel

Invoke this method to open a panel in the menu.

(

panel

_HTMLElement_

`null`

Panel (UL) to open.

)

### Off-Canvas add-on

Creates an off-canvas drawer. This drawer can be populated with any
kind of content.

.Methods for the `offcanvas` add-on
[cols="3,2,2,5a", options="header", width="100%", role="table-responsive"]
|===============================================================================
|Method |Datatype |Default |Description

|`open`
|NA
|NA
|Invoke this method to open the menu.

.Example
[source, html]
----
<div>
  <a class="mt-3" href="#mmenu">Open the menu</a>
</div>

<script>
  const drawer = menu.offcanvas ({
    // drawer options
    position:         "left"
  });

  _open_menu.addEventListener( "click", function (e) {
    e.preventDefault();
    drawer.open();
  });
</script>
----

|`close`
|NA
|NA
|Invoke this method to close the menu.

.Example
[source, html]
----
<div>
  <a class="mt-3" href="#mmenu">Open the menu</a>
</div>

<script>
  const drawer = menu.offcanvas ({
    // drawer options
    position:         "left"
  });

  _open_menu.addEventListener( "click", function (e) {
    e.preventDefault();
    drawer.close();
  });
</script>
----
|===============================================================================
