---
title:                                  Copyright 
tagline:                                software and content
description:                            Copyright for Software and Content

tags:                                   [ Copyright, Software, Content ]
index:                                  []
categories:                             [ pages ]

permalink:                              /pages/public/legal/en/copyright/
regenerate:                             false

resources:                              []
resource_options:
  - attic:
      padding_top:                      400
      padding_bottom:                   50
      opacity:                          0.5 
      slides:
        - url:                          /assets/images/modules/attics/giammarco-boscaro-1920x1280.jpg
          alt:                          Photo by Giammarco Boscaro
          alignY:                       0.5
          badge:
            type:                       unsplash
            author:                     Giammarco Boscaro
            href:                       https://unsplash.com/@giamboscaro
---
:disclaimer:


== Copyright

The content and works published on this website are governed by the copyright
laws of Germany. Any duplication, processing, distribution or any form of
utilisation beyond the scope of copyright law shall require the prior written
consent of the author or authors in question.

The content provide by this are subject to German copyright law. The 
duplication, editing, distribution and any kind of exploitation outside the
limits of copyright require the written consent of respective author or 
creator.

Downloads and copies of this site are for private use only, not
commercial use.

As far as the content on this page was not created by the operator, the 
copyrights of third parties are respected. Nevertheless, you were on one
copyright infringement, we friendly ask for a corresponding note.

ifdef::disclaimer[]
== Disclaimer

The contents of the website were created with the greatest possible care 
and to the best of our conscience. Nevertheless, the provider of this 
website assumes no responsibility for the topicality, completeness and 
accuracy of the pages and content provided. 

=== Liability for content

As a content provider, we are responsible for our own content in accordance 
with § 7 Abs.1 TMG According to §§ 8 to 10 TMG However, as a service provider 
we are not obliged to transmit or transmit to monitor stored foreign 
information or according to circumstances research that indicates unlawful 
activity.

Obligations to remove or block the use of information according to the general 
laws remain unaffected. A related Liability, however, is only from the date of 
knowledge of a concrete Infringement possible. Upon becoming aware of appropriate
Violations, we will remove this content immediately.

=== Liability for linked pages

Our offer contains links to external websites of third parties, on their 
contents we have no influence. That's why we can for this foreign content
also assume no liability. For the contents of the linked pages is always
the respective provider or operator of the pages responsible.

The linked pages were at the time of linking to possible legal violations 
checked. Illegal content was, at the time of linking those content pages, not 
recognizable.

However, a permanent content control of the linked pages is without concrete 
evidence of an infringement unreasonable. Becoming aware of violations, we 
will promptly such links remove.
endif::[]




