---
title:                                  Change Me
tagline:                                The very first file you'll change
description:                            Test page for content changes

tags:                                   [ Start, Template, Web, Day, Jekyll ]
index:                                  []
categories:                             [ pages ]

permalink:                              /pages/public/start/change_me_first/
regenerate:                             false

#resources:                             []
resource_options:
  - toccer:
      collapseDepth:                    2
  - attic:
      opacity:                          0.5
      slides:
        - url:                          /assets/images/widescreen/featured-1920x800.jpg
          alt:                          featured-1920x800
---

// Enable the Liquid Preprocessor
//
:page-liquid:

// Set other global page attributes here
// -------------------------------------------------------------------


== The first file to change

Change_Me_First  

lorem:sentences[5]

//////////
++++
<!-- Icon Blocks -->
<div class="row">
  <div class="col-lg-6 g-mb-30">
    <!-- Icon Blocks -->
    <div class="u-angle-v1--top-right--bg-light g-bg-pink g-color-white text-center g-rounded-5 g-py-60 g-px-30">
      <span class="u-icon-v2 g-rounded-5 g-mb-25">
        <i class="mdi mdi-account mdi-3x"></i>
      </span>
      <h3 class="h5 g-font-weight-600 mb-30">Extensive documentation</h3>
      <p class="g-color-white-opacity-0_8">We strive to embrace and drive change in our industry which allows us to keep our clients relevant.</p>
    </div>
    <!-- End Icon Blocks -->
  </div>

  <div class="col-lg-6 g-mb-30">
    <!-- Icon Blocks -->
    <div class="u-angle-v1--top-right--bg-light g-bg-teal g-color-white text-center g-rounded-5 g-py-60 g-px-30">
      <span class="u-icon-v2 g-rounded-5 g-mb-25">
        <i class="mdi mdi-account mdi-3x"></i>
      </span>
      <h3 class="h5 g-font-weight-600 mb-30">Modern design</h3>
      <p class="g-color-white-opacity-0_8">We strive to embrace and drive change in our industry which allows us to keep our clients relevant.</p>
    </div>
    <!-- End Icon Blocks -->
  </div>

<!-- Icon Blocks -->
<div class="row">
  <div class="col-lg-6 g-mb-30">
    <!-- Icon Blocks -->
    <div class="u-angle-v2--top-left--bg-dark g-bg-cyan-gradient-opacity-v1 g-color-white g-rounded-5 g-px-25 g-py-40">
      <div class="media">
        <div class="d-flex mr-4">
          <span class="d-block g-font-size-25">
            <i class="mdi mdi-account mdi-3x"></i>
          </span>
        </div>
        <div class="media-body">
          <h3 class="h4 text-uppercase g-mb-5">Contact Us</h3>
          <span class="d-block g-mb-10">1(123) 456 143</span>
          <p class="g-color-white-opacity-0_8 g-mb-0">We strive to embrace and drive change in our industry which allows us to keep our clients relevant and ready to adapt.</p>
        </div>
      </div>
    </div>
    <!-- End Icon Blocks -->
  </div>

  <div class="col-lg-6 g-mb-30">
    <!-- Icon Blocks -->
    <div class="u-angle-v2--top-left--bg-dark g-bg-cyan-gradient-opacity-v1 g-color-white g-rounded-5 g-px-25 g-py-40">
      <div class="media">
        <div class="d-flex mr-4">
          <span class="d-block g-font-size-25">
            <i class="mdi mdi-account mdi-3x"></i>
          </span>
        </div>
        <div class="media-body">
          <h3 class="h4 text-uppercase g-mb-5">Email Us</h3>
          <span class="d-block g-mb-10">support@example.com</span>
          <p class="g-color-white-opacity-0_8 g-mb-0">We strive to embrace and drive change in our industry which allows us to keep our clients relevant and ready to adapt.</p>
        </div>
      </div>
    </div>
    <!-- End Icon Blocks -->
  </div>


</div>
<!-- End Icon Blocks -->
++++
//////////

//lorem:sentences[3]

//lorem:words[3]

//////////

[disk]
* one
* two
* three

icon:tags[role="md-pink"] Icon based Check List

* [*] checked
* [x] also checked
* [ ] not checked
*     normal list item

icon:tags[role="md-blue"] Interactive Check List

[%interactive]
* [*] checked
* [x] also checked
* [ ] not checked
*     normal list item

//////////

