---
title:                                  Framer
tagline:                                automatic resizing of iFrames
description:                            iFrame Resizer

tags:                                   [ Manual, Framer ]
index:                                  [ iFrame, Resizer ]
categories:                             [ pages ]

permalink:                              /pages/private/user_guide/framer/
regenerate:                             false

#resources:                             []
resource_options:
  - toccer:
      collapseDepth:                    2
#  - attic:
#      opacity:                          0.5
#      slides:
#        - url:                          /assets/images/widescreen/featured-1920x800.jpg
#          alt:                          featured-1920x800
---

// Enable the Liquid Preprocessor
// -----------------------------------------------------------------------------
:page-liquid:

// Set other global page attributes here
// -----------------------------------------------------------------------------

This library enables the automatic resizing of the height and width of
both same and cross domain iFrames to fit their contained content. It
provides a range of features to address the most common issues with
using iFrames, these include:

* Height and width resizing of the iFrame to content size.
* Works with multiple and nested iFrames.
* Domain authentication for cross domain iFrames.
* Provides a range of page size calculation methods to support complex
CSS layouts.
* Detects changes to the DOM that can cause the page to resize using
https://developer.mozilla.org/en/docs/Web/API/MutationObserver[MutationObserver].
* Detects events that can cause the page to resize (Window Resize, CSS
Animation and Transition, Orientation Change and Mouse events).
* Simplified messaging between iFrame and host page via
https://developer.mozilla.org/en-US/docs/Web/API/window.postMessage[postMessage].
* Fixes in page links in iFrame and supports links between the iFrame
and parent page.
* Provides custom sizing and scrolling methods.
* Exposes parent position and viewport size to the iFrame.
* Works with http://viewerjs.org/[ViewerJS] to support PDF and ODF
documents.
* Fallback support down to IE8.

== Getting started

The package contains two minified JavaScript files in the js folder. The
first
(https://raw.githubusercontent.com/davidjbradshaw/iframe-resizer/master/js/iframeResizer.min.js[iframeResizer.min.js])
is for the page hosting the iFrames. It can be called with *native*
JavaScript;

[source, js]
----
var iframes = iFrameResize( [{options}], [css selector] || [iframe] );
----

or via *jQuery*. (See link:#browser-compatibility[notes] below for using
native version with IE8).

[source, js]
----
$('iframe').iFrameResize( [{options}] );
----

The second file
(https://raw.github.com/davidjbradshaw/iframe-resizer/master/js/iframeResizer.contentWindow.min.js[iframeResizer.contentWindow.min.js])
is a *native* JavaScript file that needs placing in the page contained
within your iFrame. _This file is designed to be a guest on someone
else’s system, so has no dependencies and won’t do anything until it’s
activated by a message from the containing page_.

=== Typical setup

The normal configuration is to have the iFrame resize when the browser
window changes size or the content of the iFrame changes. To set this up
you need to configure one of the dimensions of the iFrame to a
percentage and tell the library to only update the other dimension.
Normally you would set the width to 100% and have the height scale to
fit the content.

[source, js]
----
<style>iframe{width:100%}</style>
<iframe src="http://anotherdomain.com/iframe.html" scrolling="no"></iframe>
<script>iFrameResize({log:true})</script>
----

Note that scrolling is set to ‘no’ in the iFrame tag, as older versions
of IE don’t allow this to be turned off in code and can just slightly
add a bit of extra space to the bottom of the content that it doesn’t
report when it returns the height. If you have problems, check the
link:#troubleshooting[troubleshooting] section below.

==== Example

To see this working take a look at this
http://davidjbradshaw.com/iframe-resizer/example/[example] and watch the
https://developer.mozilla.org/en-US/docs/Tools/Web_Console[console].

== Options

=== log

[source, js]
----
default: false
type:    boolean
----

Setting the `log` option to true will make the scripts in both the host
page and the iFrame output everything they do to the JavaScript console
so you can see the communication between the two scripts.

=== autoResize

[source, js]
----
default: true
type:    boolean
----

When enabled changes to the Window size or the DOM will cause the iFrame
to resize to the new content size. Disable if using size method with
custom dimensions.

_Note: When set to false the iFrame will still inititally size to the
contained content, only additional resizing events are disabled._

=== bodyBackground

[source, js]
----
default: null
type:    string
----

Override the body background style in the iFrame.

=== bodyMargin

[source, js]
----
default: null
type:    string || number
----

Override the default body margin style in the iFrame. A string can be
any valid value for the CSS margin attribute, for example ‘8px 3em’. A
number value is converted into px.

=== checkOrigin

[source, js]
----
default: true
type:    boolean || array
----

When set to true, only allow incoming messages from the domain listed in
the `src` property of the iFrame tag. If your iFrame navigates between
different domains, ports or protocols; then you will need to provide an
array of URLs or disable this option.

=== inPageLinks

[source, js]
----
default: false
type:    boolean
----

When enabled in page linking inside the iFrame and from the iFrame to
the parent page will be enabled.

=== interval

[source, js]
----
default: 32  (in ms)
type:    number
----

In browsers that don’t support
https://developer.mozilla.org/en/docs/Web/API/MutationObserver[mutationObserver],
such as IE10, the library falls back to using setInterval, to check for
changes to the page size. The default value is equal to two frame
refreshes at 60Hz, setting this to a higher value will make screen
redraws noticeable to the user.

Setting this property to a negative number will force the interval check
to run instead of
https://developer.mozilla.org/en/docs/Web/API/MutationObserver[mutationObserver].

Set to zero to disable.

=== heightCalculationMethod

[source, js]
----
default: 'bodyOffset'
values:  'bodyOffset' | 'bodyScroll' | 'documentElementOffset' | 'documentElementScroll' |
         'max' | 'min' | 'grow' | 'lowestElement' | 'taggedElement'
----

By default the height of the iFrame is calculated by converting the
margin of the `body` to _px_ and then adding the top and bottom figures
to the offsetHeight of the `body` tag.

In cases where CSS styles causes the content to flow outside the `body`
you may need to change this setting to one of the following options.
Each can give different values depending on how CSS is used in the page
and each has varying side-effects. You will need to experiment to see
which is best for any particular circumstance.

* *bodyScroll* uses `document.body.scrollHeight`
* *documentElementOffset* uses `document.documentElement.offsetHeight`
* *documentElementScroll* uses `document.documentElement.scrollHeight`
* *max* takes the largest value of the main four options
* *min* takes the smallest value of the main four options
* *grow* same as *max* but disables the double resize that is used to
  workout if the iFrame needs to shrink. This provides much better
  performance if your iFrame will only ever increase in size
* *lowestElement* Loops though every element in the the DOM and finds
  the lowest bottom point
* *taggedElement* Finds the bottom of the lowest element with a
  `data-iframe-height` attribute

[NOTE]
====
_*If the default option doesn’t work then the best solutions is to
either to use* taggedElement, *or to use* lowestElement *in modern
browsers and* max *in IE10 downwards.*_

[source, js]
----
// Detect IE10 and below
var isOldIE = (navigator.userAgent.indexOf("MSIE") !== -1);

iFrameResize( {
    heightCalculationMethod: isOldIE ? 'max' : 'lowestElement'
});
----
====

NOTE: The *lowestElement* option is the most reliable way of determining
the page height. However, it does have a performance impact in older
versions of IE. In one screen refresh (16ms) Chrome can calculate the
position of around 10,000 html nodes, whereas IE 8 can calculate
approximately 50. The *taggedElement* option provides much greater
performance by limiting the number of elements that need their position
checked.

NOTE: The *bodyScroll*, *documentElementScroll*, *max* and *min* options
can cause screen flicker and will prevent the link:#interval[interval]
trigger downsizing the iFrame when the content shrinks. This is mainly
an issue in IE 10 and below, where the
https://developer.mozilla.org/en/docs/Web/API/MutationObserver[mutationObserver]
event is not supported. To overcome this you need to manually trigger a
page resize by calling the
link:#size-customheight-customwidth[parentIFrame.size()] method when you
remove content from the page.

=== maxHeight|maxWidth

[source, js]
----
default: infinity
type:    integer
----

Set maximum height/width of iFrame.

=== minHeight / minWidth

[source, js]
----
default: 0
type:    integer
----

Set minimum height/width of iFrame.

=== resizeFrom

[source, js]
----
default: 'parent'
values: 'parent', 'child'
----

Listen for resize events from the parent page, or the iFrame. Select the
‘child’ value if the iFrame can be resized independently of the browser
window. _Selecting this value can cause issues with some height
calculation methods on mobile devices_.

=== scrolling

[source, js]
----
default: false
type:    boolean
----

Enable scroll bars in iFrame.

=== sizeHeight

[source, js]
----
default: true
type:    boolean
----

Resize iFrame to content height.

=== sizeWidth

[source, js]
----
default: false
type:    boolean
----

Resize iFrame to content width.

=== tolerance

[source, js]
----
default: 0
type:    integer
----

Set the number of pixels the iFrame content size has to change by,
before triggering a resize of the iFrame.

=== widthCalculationMethod

[source, js]
----
default: 'scroll'
values:  'bodyOffset' | 'bodyScroll' | 'documentElementOffset' | 'documentElementScroll' |
         'max' | 'min' | 'scroll' | 'rightMostElement' | 'taggedElement'
----

By default the width of the page is worked out by taking the greater of
the *documentElement* and *body* scrollWidth values.

Some CSS technics may require you to change this setting to one of the
following options. Each can give different values depending on how CSS
is used in the page and each has varying side-effects. You will need to
experiment to see which is best for any particular circumstance.

* *bodyOffset* uses `document.body.offsetWidth`
* *bodyScroll* uses `document.body.scrollWidth`
* *documentElementOffset* uses `document.documentElement.offsetWidth`
* *documentElementScroll* uses `document.documentElement.scrollWidth`
* *scroll* takes the largest value of the two scroll options
* *max* takes the largest value of the main four options
* *min* takes the smallest value of the main four options
* *rightMostElement* Loops though every element in the the DOM and finds
  the right most point
* *taggedElement* Finds the left most element with a `data-iframe-width`
  attribute

NOTE: _The *rightMostElement* option is the most reliable way of
determining the page width. However, it does have a performance impact
in older versions of IE. In one screen refresh (16ms) Chrome can
calculate the position of around 10,000 html nodes, whereas IE 8 can
calculate approximately 50. The *taggedElement* option provides much
greater performance by limiting the number of elements that need their
position checked._

NOTE: _The *bodyScroll*, *documentElementScroll*, *max* and *min* options
can cause screen flicker and will prevent the link:#interval[interval]
trigger downsizing the iFrame when the content shrinks. This is mainly
an issue in IE 10 and below, where the
https://developer.mozilla.org/en/docs/Web/API/MutationObserver[mutationObserver]
event is not supported. To overcome this you need to manually trigger a
page resize by calling the
link:#size-customheight-customwidth[parentIFrame.size()] method when you
remove content from the page._

== Callback Methods

=== closedCallback

[source, js]
----
type: function (iframeID)
----

Called when iFrame is closed via `parentIFrame.close()` or
`iframe.iframeResizer.close()` methods. See below for details.

=== initCallback

[source, js]
----
type: function (iframe)
----

Initial setup callback function.

=== messageCallback

[source, js]
----
type: function ({iframe,message})
----

Receive message posted from iFrame with the `parentIFrame.sendMessage()`
method.

=== resizedCallback

[source, js]
----
type: function ({iframe,height,width,type})
----

Function called after iFrame resized. Passes in messageData object
containing the *iFrame*, *height*, *width* and the *type* of event that
triggered the iFrame to resize.

=== scrollCallback

[source, js]
----
type: function ({x,y})
----

Called before the page is repositioned after a request from the iFrame,
due to either an in page link, or a direct request from either
link:#scrolltoxy[parentIFrame.scrollTo()] or
link:#scrolltooffsetxy[parentIFrame.scrollToOffset()]. If this callback
function returns false, it will stop the library from repositioning the
page, so that you can implement your own animated page scrolling
instead.

== IFrame Page Options

The following options can be set from within the iFrame page by creating
a `window.iFrameResizer` object before the JavaScript file is loaded
into the page.

[source, js]
----
<script>
    window.iFrameResizer = {
        targetOrigin: 'http://mydomain.com'
    }
</script>
<script src="js/iframeresizer.contentwindow.js"></script>
----

=== targetOrigin

[source, js]
----
default: '*'
type: string
----

This option allows you to restrict the domain of the parent page, to
prevent other sites mimicing your parent page.

=== messageCallback

[source, js]
----
type: function (message)
----

Receive message posted from the parent page with the
`iframe.iFrameResizer.sendMessage()` method (See below for details).

=== readyCallback

[source, js]
----
type: function()
----

This function is called once iFrame-Resizer has been initialized after
receiving a call from the parent page. If you need to call any of the
parentIFrame methods (See below) during page load, then they should be
called from this callback.

height|widthCalculationMethod

[source, js]
----
default: null
type: string
----

These options can be used to override the option set in the parent page
(See above for details on available values). This can be useful when
moving between pages in the iFrame that require different values for
these options.


== IFrame Page Methods

These methods are available in the iFrame via the `window.parentIFrame`
object. These method should be contained by a test for the
`window.parentIFrame` object, in case the page is not loaded inside an
iFrame. For example:

[source, js]
----
if ('parentIFrame' in window) {
    parentIFrame.close();
}
----

=== autoResize ()

autoResize([bool])

Turn autoResizing of the iFrame on and off. Returns bool of current
state.

=== close ()

Remove the iFrame from the parent page.

=== getId ()

Returns the ID of the iFrame that the page is contained in.

=== getPageInfo ()

getPageInfo(callback || false)

Ask the containing page for its positioning coordinates. You need to
provide a callback which receives an object with the following
properties:

* *clientHeight* The height of the viewport in pixels
* *clientWidth* The width of the viewport in pixels
* *offsetLeft* The number of pixels between the left edge of the
containing page and the left edge of the iframe
* *offsetTop* The number of pixels between the top edge of the
containing page and the top edge of the iframe
* *scrollLeft* The number of pixels between the left edge of the iframe
and the left edge of the iframe viewport
* *scrollTop* The number of pixels between the top edge of the iframe
and the top edge of the iframe viewport

Your callback function will be recalled when the parent page is scrolled
or resized.

Pass `false` to disable the callback.

=== scrollTo ()

scrollTo(x,y)

Scroll the parent page to the coordinates x and y.

=== scrollToOffset ()

scrollToOffset(x,y)

Scroll the parent page to the coordinates x and y relative to the
position of the iFrame.


=== sendMessage ()

sendMessage(message,[targetOrigin])

Send data to the containing page, `message` can be any data type that
can be serialized into JSON. The `targetOrigin` option is used to
restrict where the message is sent to; to stop an attacker mimicking
your parent page. See the MDN documentation on
https://developer.mozilla.org/en-US/docs/Web/API/Window.postMessage[postMessage]
for more details.

=== setHeightCalculationMethod()

setHeightCalculationMethod(heightCalculationMethod)

Change the method use to workout the height of the iFrame.

=== size ()

size ([customHeight],[ customWidth])

Manually force iFrame to resize. This method optionally accepts two
arguments: *customHeight* & *customWidth*. To use them you need first to
disable the `autoResize` option to prevent auto resizing and enable the
`sizeWidth` option if you wish to set the width.

[source, js]
----
iFrameResize({
    autoResize: false,
    sizeWidth: true
});
----

Then you can call the `size` method with dimensions:

[source, js]
----
if ('parentIFrame' in window) {
    parentIFrame.size(100); // Set height to 100px
}
----

== IFrame Object Methods

Once the iFrame has been initialized, an `iFrameResizer` object is bound
to it. This has the following methods available.

=== close ()

Remove the iFrame from the page.

=== moveToAnchor ()

moveToAnchor(anchor)

Move to anchor in iFrame.

=== resize()

Tell the iFrame to resize itself.

=== sendMessage ()

sendMessage(message,[targetOrigin])

Send data to the containing page, `message` can be any data type that
can be serialized into JSON. The `targetOrigin` option is used to
restrict where the message is sent to, in case your iFrame navigates
away to another domain.

== Troubleshooting

The first steps to investigate a problem is to make sure you are using
the latest version and then enable the link:#log[log] option, which
outputs everything that happens to the
https://developers.google.com/chrome-developer-tools/docs/console#opening_the_console[JavaScript
Console]. This will enable you to see what both the iFrame and host page
are up to and also see any JavaScript error messages.

Solutions for the most common problems are outlined in this section. If
you need futher help, then please ask questions on
http://stackoverflow.com/questions/tagged/iframe-resizer[StackOverflow]
with the `iframe-resizer` tag.

Bug reports and pull requests are welcome on the
https://github.com/davidjbradshaw/iframe-resizer/issues[issue tracker].
Please read the
https://github.com/davidjbradshaw/iframe-resizer/blob/master/CONTRIBUTING.md[contributing
guidelines] before openning a ticket, as this will ensure a faster
resolution.

=== IFrame not sizing correctly

If a larger element of content is removed from the normal document flow,
through the use of absolute positioning, it can prevent the browser
working out the correct size of the page. In such cases you can change
the link:#heightcalculationmethod[heightCalculationMethod] to uses one
of the other sizing methods.

=== IFrame not downsizing

The most likely cause of this problem is having set the height of an
element to be 100% of the page somewhere in your CSS. This is normally
on the `html` or `body` elements, but it could be on any element in the
page. This can sometimes be got around by using the `taggedElement`
height calculation method and added a `data-iframe-height` attribute to
the element that you want to define the bottom position of the page. You
may find it useful to use `position: relative` on this element to define
a bottom margin or allow space for a floating footer.

Not having a valid
http://en.wikipedia.org/wiki/Document_type_declaration[HTML document
type] in the iFrame can also sometimes prevent downsizing. At it’s most
simplest this can be the following.

[source, js]
----
<!DOCTYPE html>
----

=== IFrame not resizing

The most common cause of this is not placing the
https://raw.github.com/davidjbradshaw/iframe-resizer/master/js/iframeResizer.contentWindow.min.js[iframeResizer.contentWindow.min.js]
script inside the iFramed page. If the other page is on a domain outside
your control and you can not add JavaScript to that page, then now is
the time to give up all hope of ever getting the iFrame to size to the
content. As it is impossible to work out the size of the contained page,
without using JavaScript on both the parent and child pages.


=== IFrame not detecting :hover events

If your page resizes via CSS `:hover` events, these won’t be detected by
default. It is however possible to create `mouseover` and `mouseout`
event listeners on the elements that are resized via CSS and have these
events call the
link:##parentiframesize-customheight-customwidth[parentIFrame.size()]
method. With jQuery this can be done as follows

[source, js]
----
function resize(){
    if ('parentIFrame' in window) {
        // Fix race condition in FireFox with setTimeout
        setTimeout(parentIFrame.size.bind(parentIFrame),0);
    }
}

$(*Element with hover style*).hover(resize);
----

=== IFrame not resize on textarea

Both FireFox and the WebKit based browsers allow the user to resize
`textarea` input boxes. Unfortunately the WebKit browsers don’t trigger
the mutation event when this happens. This can be worked around to some
extent with the following code.

[source, js]
----
function store(){
    this.x = this.offsetWidth;
    this.y = this.offsetHeight;
}

$('textarea').each(store).on('mouseover mouseout',function(){
    if (this.offsetWidth !== this.x || this.offsetHeight !== this.y){
        store.call(this);
        if ('parentIFrame' in window){
            parentIFrame.size();
        }
    }
});
----

=== IFrame flickers

Some of the alternate link:#heightcalculationmethod[height calculation
methods], such as *max* can cause the iFrame to flicker. This is due to
the fact that to check for downsizing, the iFrame first has to be
downsized before the new height can be worked out. This effect can be
reduced by setting a link:#minheight--minwidth[minSize] value, so that
the iFrame is not reset to zero height before regrowing.

In modern browsers, if the default link:#heightcalculationmethod[height
calculation method] does not work, then it is normally best to use
*lowestElement*, which is flicker free, and then provide a fallback to
*max* in IE10 downwards.

[source, js]
----
var isOldIE = (navigator.userAgent.indexOf("MSIE") !== -1); // Detect IE10 and below

iFrameResize({
    heightCalculationMethod: isOldIE ? 'max' : 'lowestElement',
    minSize:100
});
----

NOTE: Please see the notes section under
link:#heightcalculationmethod[heightCalculationMethod] to understand the
limitations of the different options.

=== ParentIFrame not found

The `parentIFrame` object is created once the iFrame has been initially
resized. If you wish to use it during page load you will need call it
from the readyCallback.

[source, js]
----
<script>
    window.iFrameResizer = {
        readyCallback: function(){
            var myId = window.parentIFrame.getId();
            console.log('The ID of the iFrame in the parent page is: '+myId);
        }
    }
</script>
<script src="js/iframeresizer.contentwindow.js"></script>
----

=== Unexpected message received

By default the origin of incoming messages is checked against the `src`
attribute of the iFrame. If they don’t match an error is thrown. This
behaviour can be disabled by setting the link:#checkorigin[checkOrigin]
option to *false*.

== PDF and OpenDocument files

It is not possible to add the required JavaScript to PDF and ODF files.
However, you can get around this limitation by using
http://viewerjs.org/[ViewerJS] to render these files inside a HTML page,
that also contains the iFrame JavaScript file
(https://raw.github.com/davidjbradshaw/iframe-resizer/master/js/iframeResizer.contentWindow.min.js[iframeResizer.contentWindow.min.js]).
