#collections:

  # ----------------------------------------------------------------------------
  # Component Default Settings
  #
  # - label:          J1 Component Configuration
  #   name:           component_default_settings
  #   files:

      # ------------------------------------------------------------------------
      # Banner settings
      #
      - label: Banner Settings
        name:  banner_settings
        file:  packages/400_template_site/_cc_test_data/_data/blocks/banner.yml
        fields:

          # --------------------------------------------------------------------
          # About this configuration (used for J1 CC only)
          #
          - label:  about
            name:   about_config
            widget: object
            fields:
              - { label: title,     name: title,    widget: string, hint: General J1 Template settings to specify ALL resources used by a site or a layout }
              - { label: scope,     name: scope,    widget: string, hint: Scope the data is used }
              - { label: data file, name: location, widget: string, hint: Folder the configuration file is stored (relative to site root) }

          # --------------------------------------------------------------------
          # USER settings
          #
          - label:  User settings
            name:   settings
            widget: object
            fields:
              # ----------------------------------------------------------------
              # Divider Banner properties
              #
              - label:        Divider Banner
                name:         divider
                widget:       list
                fields:
                  - label:    banner name
                    name:     name
                    widget:   string
                    hint:     Arbitrary name of a resource
                  - label:    Properties
                    name:     banner
                    widget:   object
                    hint:     Specifies all properties of a banner
                    fields:
                      - { label: enabled,         name: enabled,        widget: boolean,  hint: Enables or Disables the module }
                      - { label: id,              name: id,             widget: string,   hint: Unique resource ID }
                      - { label: comment,         name: comment,        widget: string,   hint: TBD }
                      - { label: type,            name: type,           widget: string,   hint: TBD }

              # ----------------------------------------------------------------
              # Teaser Banner properties
              #
              - label:        Teaser Banner
                name:         teaser
                widget:       list
                fields:
                  - label:    banner name
                    name:     name
                    widget:   string
                    hint:     Arbitrary name of a banner
                  - label:    Properties
                    name:     banner
                    widget:   object
                    hint:     Specifies all properties of a banner
                    fields:
                      - { label: enabled,             name: enabled,            widget: boolean,  hint: Enables or Disables the module }
                      - { label: id,                  name: id,                 widget: string,   hint: Unique resource ID }
                      - { label: comment,             name: comment,            widget: string,   hint: TBD }
                      - { label: type,                name: type,               widget: string,   hint: TBD }
                      - { label: Icon Family,         name: icon_family,        widget: select,   options: [ MDI, FA ], hint: Default Icon Family for the Navigation Module }
                      - { label: style,               name: style,              widget: select,   options: [ light, dark ], hint: TBD }
                      - { label: background color 1,  name: background_color_1, widget: string,   hint: TBD }
                      - { label: background color 2,  name: background_color_2, widget: string,   hint: TBD }
                      - { label: lane span,           name: lane_span,          widget: select,   options: [ fixed, fluid ], hint: TBD }
                      - { label: helper classes,      name: helper_classes,     widget: string,   hint: Unique resource ID }
                      - label:    Boxes
                        name:     boxes
                        widget:   list
                        hint:     Specifies the content portion of a banner
                        fields:
                          - label:    Content
                            name:     name
                            widget:   string
                          - label:    Properties
                            name:     box
                            widget:   object
                            fields:
                              - { label: enabled,     name: enabled,      widget: boolean,  hint: Enables or Disables the module }
                              - { label: width,       name: width,        widget: number,   min: 3, max: 12, hint: TBD }
                              - { label: type,        name: type,         widget: select,   options: [ text ], hint: TBD }
                              - { label: animate,     name: animate,      widget: select,   options: [ fadeInUp ], hint: TBD }
                              - { label: title,       name: title,        widget: string,   hint: TBD }
                              - { label: description, name: description,  widget: text,     hint: TBD }
                              - { label: tagline,     name: tagline,      widget: string,   hint: TBD }

                              - label:    Buttons
                                name:     buttons
                                widget:   list
                                hint:     Defines all buttons
                                fields:
                                  - label:    Button Name
                                    name:     name
                                    widget:   string
                                  - label:    Button settings
                                    name:     button
                                    widget:   object
                                    hint:     Specifies buttons used this teaser
                                    fields:
                                      - { label: text,        name: text,       widget: string,   hint: TBD }
                                      - { label: class,       name: class,      widget: string,   hint: TBD }
                                      - { label: icon,        name: icon,       widget: string,   hint: TBD }
                                      - { label: icon_color,  name: icon_color, widget: string,   hint: TBD }
                                      - { label: icon_size,   name: icon_size,  widget: string,   hint: TBD }
                                      - { label: href,        name: href,       widget: string,   hint: TBD }


              # ----------------------------------------------------------------
              # Image Banner properties
              #
              - label:        Image Banner
                name:         image
                widget:       list
                fields:
                  - label:    banner name
                    name:     name
                    widget:   string
                    hint:     Arbitrary name of a banner
                  - label:    Properties
                    name:     banner
                    widget:   object
                    hint:     Specifies all properties of a banner
                    fields:
                      - { label: enabled,             name: enabled,            widget: boolean,  hint: Enables or Disables the module }
                      - { label: id,                  name: id,                 widget: string,   hint: Unique resource ID }
                      - { label: comment,             name: comment,            widget: string,   hint: TBD }
                      - { label: type,                name: type,               widget: string,   hint: TBD }
                      - { label: background color 1,  name: background_color_1, widget: string,   hint: TBD }
                      - { label: background color 2,  name: background_color_2, widget: string,   hint: TBD }
                      - { label: lane span,           name: lane_span,          widget: select,   options: [ fixed, fluid ], hint: TBD }
                      - { label: helper classes,      name: helper_classes,     widget: string,   hint: Unique resource ID }
                      - label:    Boxes
                        name:     boxes
                        widget:   list
                        hint:     Specifies the content portion of a banner
                        fields:
                          - label:    Content
                            name:     name
                            widget:   string
                          - label:    Properties
                            name:     box
                            widget:   object
                            fields:
                              - { label: enabled,           name: enabled,          widget: boolean,  hint: TBD }
                              - { label: gridify,           name: gridify,          widget: boolean,  hint: TBD }
                              - { label: size_y,            name: size_y,           widget: number,   min: 300, max: 600, hint: TBD }
                              - { label: darken,            name: darken,           widget: number,   min: 1, max: 10, hint: TBD }
                              - { label: background image,  name: background_image, widget: string,   hint: TBD }


              # ----------------------------------------------------------------
              # Parallax Banner
              #
              - label:        Parallax Banner
                name:         parallax
                widget:       list
                fields:
                  - label:    banner name
                    name:     name
                    widget:   string
                    hint:     Arbitrary name of a resource
                  - label:    Properties
                    name:     banner
                    widget:   object
                    hint:     Specifies all properties of a banner
                    fields:
                      - { label: enabled,             name: enabled,            widget: boolean,  hint: Enables or Disables the module }
                      - { label: id,                  name: id,                 widget: string,   hint: Unique resource ID }
                      - { label: comment,             name: comment,            widget: string,   hint: TBD }
                      - { label: type,                name: type,               widget: string,   hint: TBD }
                      - { label: style,               name: style,              widget: string,   hint: TBD }
                      - { label: background color 1,  name: background_color_1, widget: string,   hint: TBD }
                      - { label: background color 2,  name: background_color_2, widget: string,   hint: TBD }
                      - { label: lane span,           name: lane_span,          widget: select,   options: [ fixed, fluid ], hint: TBD }
                      - { label: helper classes,      name: helper_classes,     widget: string,   hint: Unique resource ID }
                      - label:    Boxes
                        name:     boxes
                        widget:   list
                        hint:     Specifies the content portion of a banner
                        fields:
                          - label:    Content
                            name:     name
                            widget:   string
                          - label:    Properties
                            name:     box
                            widget:   object
                            fields:
                              - { label: enabled,           name: enabled,          widget: boolean,  hint: TBD }
                              - { label: type,              name: type,             widget: select,   options: [ quote ], hint: TBD }
                              - { label: cite,              name: cite,             widget: string,   hint: TBD }
                              - { label: cite text,         name: cite_text,        widget: text,     hint: TBD }
                              - { label: cite color,        name: cite_color,       widget: string,   hint: TBD }
                              - { label: gridify,           name: gridify,          widget: boolean,  hint: TBD }
                              - { label: size_y,            name: size_y,           widget: number,   min: 300, max: 600, hint: TBD }
                              - { label: darken,            name: darken,           widget: number,   min: 1, max: 10, hint: TBD }
                              - { label: background_image,  name: background_image, widget: string,   hint: TBD }


              # ----------------------------------------------------------------
              # News Banner properties
              #
              - label:  News Banner
                name:   news
                widget: list
                fields:
                  - label:    banner name
                    name:     name
                    widget:   string
                    hint:     Arbitrary name of a banner
                  - label:    Properties
                    name:     banner
                    widget:   object
                    hint:     Specifies all properties of a banner
                    fields:
                      - { label: enabled,             name: enabled,            widget: boolean,  hint: Enables or Disables the module }
                      - { label: id,                  name: id,                 widget: string,   hint: Unique resource ID }
                      - { label: comment,             name: comment,            widget: string,   hint: TBD }
                      - { label: type,                name: type,               widget: string,   hint: TBD }
                      - { label: background color 1,  name: background_color_1, widget: string,   hint: TBD }
                      - { label: background color 2,  name: background_color_2, widget: string,   hint: TBD }
                      - { label: lane span,           name: lane_span,          widget: select,   options: [ fixed, fluid ], hint: TBD }
                      - { label: helper classes,      name: helper_classes,     widget: string,   hint: Unique resource ID }
                      - label:    Boxes
                        name:     boxes
                        widget:   list
                        hint:     Specifies the content portion of a banner
                        fields:
                          - label:    Content
                            name:     name
                            widget:   string
                          - label:    Properties
                            name:     box
                            widget:   object
                            fields:
                              - { label: enabled,   name: enabled,  widget: boolean,  hint: TBD }
                              - { label: type,      name: type,     widget: string,   hint: TBD }
                              - { label: title,     name: title,    widget: string,   hint: TBD }
                              - { label: category,  name: category, widget: string,   hint: TBD }

