#collections:

  # ----------------------------------------------------------------------------
  # Component Default Settings
  #
  # - label:          J1 Component Configuration
  #   name:           component_default_settings
  #   files:

      # ------------------------------------------------------------------------
      # Panel settings
      #
      - label: Panel Settings
        name:  panel_settings
        file:  packages/400_template_site/_cc_test_data/_data/blocks/panel.yml
        fields:

          # --------------------------------------------------------------------
          # About this configuration (used for J1 CC only)
          #
          - label:  about
            name:   about_config
            widget: object
            fields:
              - { label: title,     name: title,    widget: string, hint: General J1 Template settings to specify ALL resources used by a site or a layout }
              - { label: scope,     name: scope,    widget: string, hint: Scope the data is used }
              - { label: data file, name: location, widget: string, hint: Folder the configuration file is stored (relative to site root) }

          # --------------------------------------------------------------------
          # USER settings
          #
          - label:  User settings
            name:   settings
            widget: object
            fields:

              # ----------------------------------------------------------------
              # INTRO Panel properties
              #
              - label:  Intro Panel
                name:   intro
                widget: list
                fields:
                  - label:    panel name
                    name:     name
                    widget:   string
                    hint:     Arbitrary name of a panel
                  - label:    Properties
                    name:     panel
                    widget:   object
                    hint:     Specifies all properties of a panel
                    fields:
                      - { label: enabled,             name: enabled,            widget: boolean,  hint: Enables or Disables the module }
                      - { label: id,                  name: id,                 widget: string,   hint: Unique resource ID }
                      - { label: comment,             name: comment,            widget: string,   hint: TBD }
                      - { label: type,                name: type,               widget: string,   hint: TBD }
                      - { label: Icon Family,         name: icon_family,        widget: select,   options: [ MDI, FA ], hint: Default Icon Family for the Navigation Module }
                      - { label: style,               name: style,              widget: select,   options: [ flat, raised ], hint: TBD }
                      - { label: lane span,           name: lane_span,          widget: select,   options: [ fixed, fluid ], hint: TBD }
                      - label:    Cards
                        name:     cards
                        widget:   list
                        hint:     Specifies the content portion of a panel
                        fields:
                          - label:    Content
                            name:     name
                            widget:   string
                          - label:    Properties
                            name:     card
                            widget:   object
                            fields:
                              - { label: enabled,     name: enabled,    widget: boolean,  hint: TBD }
                              - { label: type,        name: type,       widget: string,   hint: TBD }
                              - { label: title,       name: title,      widget: string,   hint: TBD }
                              - { label: tagline,     name: tagline,    widget: string,   hint: TBD }
                              - { label: icon,        name: icon,       widget: string,   hint: TBD }
                              - { label: icon_size,   name: icon_size,  widget: string,   hint: TBD }
                              - { label: icon color,  name: icon_color, widget: string,   hint: TBD }
                              - { label: text,        name: text,       widget: text,     hint: TBD }
                              - label:    Buttons
                                name:     buttons
                                widget:   list
                                hint:     Defines all buttons
                                fields:
                                  - label:    Button Name
                                    name:     name
                                    widget:   string
                                  - label:    Button settings
                                    name:     button
                                    widget:   object
                                    hint:     Specifies buttons used this teaser
                                    fields:
                                      - { label: text,        name: text,       widget: string,   hint: TBD }
                                      - { label: class,       name: class,      widget: string,   hint: TBD }
                                      - { label: icon,        name: icon,       widget: string,   hint: TBD }
                                      - { label: icon_color,  name: icon_color, widget: string,   hint: TBD }
                                      - { label: icon_size,   name: icon_size,  widget: string,   hint: TBD }
                                      - { label: href,        name: href,       widget: string,   hint: TBD }


              # ----------------------------------------------------------------
              # SERVICE Panel properties
              #
              - label:  Service Panel
                name:   service
                widget: list
                fields:
                  - label:    panel name
                    name:     name
                    widget:   string
                    hint:     Arbitrary name of a panel
                  - label:    Properties
                    name:     panel
                    widget:   object
                    hint:     Specifies all properties of a panel
                    fields:
                      - { label: enabled,             name: enabled,            widget: boolean,  hint: Enables or Disables the module }
                      - { label: id,                  name: id,                 widget: string,   hint: Unique resource ID }
                      - { label: comment,             name: comment,            widget: string,   hint: TBD }
                      - { label: type,                name: type,               widget: string,   hint: TBD }
                      - { label: Icon Family,         name: icon_family,        widget: select,   options: [ MDI, FA ], hint: Default Icon Family for the Navigation Module }
                      - { label: style,               name: style,              widget: select,   options: [ flat, raised ], hint: TBD }
                      - { label: lane span,           name: lane_span,          widget: select,   options: [ fixed, fluid ], hint: TBD }
                      - label:   Header
                        name:    header
                        widget:  object
                        fields:
                          - { label: enabled,     name: enabled,      widget: boolean,  hint: TBD }
                          - { label: title,       name: title,        widget: string,   hint: TBD }
                          - { label: description, name: description,  widget: text,   hint: TBD }
                      - label:    Cards
                        name:     cards
                        widget:   list
                        hint:     Specifies the content portion of a panel
                        fields:
                          - label:    Content
                            name:     name
                            widget:   string
                          - label:    Properties
                            name:     card
                            widget:   object
                            fields:
                              - { label: enabled,     name: enabled,    widget: boolean,  hint: TBD }
                              - { label: type,        name: type,       widget: string,   hint: TBD }
                              - { label: title,       name: title,      widget: string,   hint: TBD }
                              - { label: tagline,     name: tagline,    widget: string,   hint: TBD }
                              - { label: icon,        name: icon,       widget: string,   hint: TBD }
                              - { label: icon_size,   name: icon_size,  widget: string,   hint: TBD }
                              - { label: icon color,  name: icon_color, widget: string,   hint: TBD }
                              - { label: text,        name: text,       widget: text,     hint: TBD }
                              - label:    Services
                                name:     services
                                widget:   list
                                hint:     Specifies a list of services
                                fields:
                                  - label:    Service Name
                                    name:     name
                                    widget:   string
                                  - label:    Service Details
                                    name:     service
                                    widget:   object
                                    fields:
                                      - { label: title, name: title, widget: string, hint: TBD }
                                      - { label: href,  name: href,  widget: string, hint: TBD }


              # ----------------------------------------------------------------
              # NEWS Panel properties
              #
              - label:  News Panel
                name:   news
                widget: list
                fields:
                  - label:    panel name
                    name:     name
                    widget:   string
                    hint:     Arbitrary name of a panel
                  - label:    Properties
                    name:     panel
                    widget:   object
                    hint:     Specifies all properties of a panel
                    fields:
                      - { label: enabled,   name: enabled,    widget: boolean,  hint: Enables or Disables the module }
                      - { label: id,        name: id,         widget: string,   hint: Unique resource ID }
                      - { label: comment,   name: comment,    widget: string,   hint: TBD }
                      - { label: type,      name: type,       widget: string,   hint: TBD }                      
                      - { label: style,     name: style,      widget: select,   options: [ flat, raised ], hint: TBD }
                      - { label: title,     name: title,      widget: string,   hint: TBD }
                      - { label: tagline,   name: tagline,    widget: string,   hint: TBD }
                      - { label: lane span, name: lane_span,  widget: select,   options: [ fixed, fluid ], hint: TBD }
                      - label:    Cards
                        name:     cards
                        widget:   list
                        hint:     Specifies the content portion of a panel
                        fields:
                          - label:    Content
                            name:     name
                            widget:   string
                          - label:    Properties
                            name:     card
                            widget:   object
                            fields:
                              - { label: enabled,   name: enabled,    widget: boolean,  hint: TBD }
                              - { label: type,      name: type,       widget: string,   hint: TBD }
                              - { label: category,  name: category,   widget: string,   hint: TBD }
                              - { label: max_posts, name: max_posts,  widget: number,   min: 1, max: 5, hint: TBD }



