#collections:

  # ----------------------------------------------------------------------------
  # Component Default Settings
  #
  # - label:          J1 Component Configuration
  #   name:           component_default_settings
  #   files:

      # ------------------------------------------------------------------------
      # FOOTER settings
      #
      - label: Footer Settings
        name:  footer_settings
        file:  packages/400_template_site/_cc_test_data/_data/blocks/footer.yml
        fields:
      
          # --------------------------------------------------------------------
          # About this configuration (used for J1 CC only)
          #
          - label:  about
            name:   about_config
            widget: object
            fields:
              - { label: title,     name: title,    widget: string, hint: General J1 Template settings to specify ALL resources used by a site or a layout }
              - { label: scope,     name: scope,    widget: string, hint: Scope the data is used }
              - { label: data file, name: location, widget: string, hint: Folder the configuration file is stored (relative to site root) }

