---
title:                                  Quickstarter
tagline:                                Starter Bundles available for J1 Template
description:                            Starter Bundles available for J1 Template
author:                                 J1 Team

tags:                                   [ Template, Download, Quickstart, Bundle]
index:                                  [ Windows, Linux, MacOS, OSX]

resources:                              [ lightbox ]
permalink:                              /pages/public/start/downloads/quickstart/
regenerate:                             false 
---

// NOTE:  General Asciidoc page attributes settings
//
:page-liquid:

{% comment %} Liquid procedures
--------------------------------------------------------------- {% endcomment %}
{% capture set_env_entry_document %}themes/{{site.template.name}}/procedures/global/set_env_entry_document.proc{%endcapture%}


// NOTE: Initialize entry document paths
//
{% include {{set_env_entry_document}} init_folders=all %}

// Load tags and urls
//
include::{includedir}/attributes.asciidoc[tag=tags]
include::{includedir}/attributes.asciidoc[tag=urls]

// Additional Asciidoc page attributes goes here
//


Quickstarter are bundles, available for Windows, Linux and MacOS. Those
bundles contain all software as a installable package needed to run Jekyll,
to develop a Web using J1 Template. All what is needed in an all-in-one
application compilation.

== Available Bundles

Creating a fully equipped Jekyll developing enviroment may take a while
anyway. If you don't want to mixup already installed applications like
Python, Ruby or NodeJS on your existing OS, you can go for J1 Quickstart.

All the tools and their environments are localized and isolated to the
application folder of the Quickstarter package and should *not* interfere
with any already of the installed programs and their resources. Simply by
setting some environment variables, the system you've prepared already for
your (Jekyll) Development Environment will be left untouched.

And you're done in 15 minutes.

=== Download a Quickstarter

Find your platform and version for the J1 Quickstarter package you need
with the following table:

include::{includedir}/tables/100_quickstart_installation_packages.asciidoc[]

Installation instructions can be found for your plattform with the sections
below.


=== J1 Starter for Windows

The J1 team prepared a full development suite for Jekyll on *Windows* that
can be easily setup. All packages needed for a full featued development
environment are bundled together; being installed by an Windows installer as
usual.

pass:[<i class="mdi mdi-windows mdi-2x mdi-md-bg-primary"></i>]
Go for link:{j1-starter-windows}[installation instructions here].


=== J1 Starter for Linux

If you don't want to mixup already installed applications like Python, Ruby
or NodeJS on your existing *Linux* OS, you can go for a Quickstart package.
All the tools and their environments are localized and isolated to the
application folder of J1 Quickstart and should *not* interfere with any
already installed programs and their ressources. Simply by setting some
environment variables, the system you've prepared already for Jekyll will be
left untouched.

pass:[<i class="mdi mdi-linux mdi-2x mdi-md-bg-primary"></i>]
Go for link:{j1-starter-linux}[installation instructions here].


=== J1 Starter for MacOS

The availability of Open Source tools and applications are not the strenght
of Apple products. Yes, Perl, Ruby, Python etc. are available out of the box
but they are pre-installed in unusable old versions. Upgrading these packages?
No choice.

You can go for *HomeBrew* to _brew_ what you need - what many people do.
The same to us - if we're on *MacOS*. But as always: installing an bunch of
software will take a while. No fun.

pass:[<i class="mdi mdi-apple mdi-2x mdi-md-bg-primary"></i>]
Go for link:{j1-starter-macos}[installation instructions here].
