---
title:                                  Roundtrip
tagline:                                step in
description:                            What to get

tags:                                   [ Page, Roundtrip ]
index:                                  [ Start, Template, Whats, Up, Readme, TL;DR ]
categories:                             [ pages ]

permalink:                              /pages/public/start/roundtrip/whats_up/
regenerate:                             false

resources:                              [ lightbox ]
resource_options:
  - attic:
      padding_top:                      400
      padding_bottom:                   50
      opacity:                          0.5
      slides:
        - url:                          /assets/images/attics/runner-1920x1200-bw.jpg
          alt:                          Photo by Alexander Redl on Unsplash
          badge:
            type:                       unsplash
            author:                     Alexander Redl
            href:                       https://unsplash.com/@alexanderredl
---

// Enable the Liquid Preprocessor
//
:page-liquid:

// Set other global page attributes here                                          
// -------------------------------------------------------------------


{% comment %} Liquid procedures
--------------------------------------------------------------- {% endcomment %}
{% capture set_env_entry_document %}themes/{{site.template.name}}/procedures/global/set_env_entry_document.proc{%endcapture%}


// NOTE: Initialize entry document paths
//
{% include {{set_env_entry_document}} init_folders=all %}

// Load tags and urls
//
include::{includedir}/attributes.asciidoc[tag=tags]
include::{includedir}/attributes.asciidoc[tag=urls]

// Additional Asciidoc page attributes goes here
//

Welcome to the Web Pages of J1 Template. If your here first time,
hopefully you get on that page first - the *ReadMe First* of the *Start*
section. For sure, there is no better place to start.

Having a menu system is great. We hope the the Navigator of J1 will help
you to explore this site, find what your are looking for. The site of J1
has grown over the last month a lot. Many documents where seeking for a home.
And we have really a bunch of them.

To get better orientated, the site is organized for *Natural Reading*. As we
use English for our international vistors (we are German), *Natural Reading*
means for a western language, reading from the left to the right, and from
top to down a page. The same to all menus, sections and pages.

For that reason, it was a good decision starting here.


== Whats up

Every main section, or larger sub-section, and most of the dropdown menus have
a ReadMe First. A Navigator is nice but the menu system does not explain what
is inside. This *gap* should be closed by the ReadMes. See them as
*too-lazy-to-search* helpers. A ReadMe give you a summary what can be found
and give some advices how to explore- where to go next. In short: don't waste
time by stumbling through deep nested dropdowns. Better: check out a ReadMe.

== Where to start

First of all, you've started already! The important first step on your way to
Jekyll is done. Congratiulations.

The *Start* section contains all you need to know what Jekyll and J1 can do
for your Web site. For your new static Web, if you want.

With this section you'll find a:

. *Roundtrip* to show you some of the main features of the Template System
  *J1*.

. *Download* area for so-called *QuickStarter*. A QuickStarter is a bundle
  (for Windows, Linux and MacOS) that contains all software as a installable
  package to run Jekyll, to develop a Web using J1 Template. All what is needed
  in an all-in-one application compilation.

. *Kickstarter* are Tutorials. The most important one to start is *Web in a Day*.
  This tutorial guides you through all the steps to build a Web - your Web using
  Jekyll and the Template J1.

== Where to go next

You should go for the *Roundtrip* first. See what you will get. As an overview
of some of the main features of *J1*. The roundtrip is a *visual* tour. No
technical stuff, nothing academic.

We recomment to read at least the article of the *QuickStarter* for your
platform you work on. You'll find out if it's needed - or helpful - to go for
a QuickStarter installation first.

Tatata, let's go more deeper and make things real - and your hands dirty. We
recomment to work on the Kickstarter *Web in a Day*. A nice one-day journey
diving into the world of Jekyll. You'll learn a lot and at the end of that day
you know what Jekyll, static webs and the template system J1 is all about.

You're welcome!

If you like, continue by walking through the roundtrip examples by starting
link:{roundtrip-present-images}[the tour here].



