---
title:                                  Roundtrip
tagline:                                themes
description:                            J1 Template Roundtrip - Template Themes

tags:                                   [ Page, Roundtrip ]
index:                                  [ Template, Roundtrip, Bootstrap, Themes ]
categories:                             [ pages ]

permalink:                              /pages/public/start/roundtrip/themes/
regenerate:                             false

resources:                              []
resource_options:
  - attic:
      padding_top:                      400
      padding_bottom:                   50
      opacity:                          0.5
      slides:
        - url:                          /assets/images/pages/roundtrip/themes-1920x1280-bw.jpg
          alt:                          Photo by Clem Onojeghuo on Unsplash
          badge:
            type:                       unsplash
            author:                     Clem Onojeghuo
            href:                       https://unsplash.com/@clemono
---

// Enable the Liquid Preprocessor 
// -----------------------------------------------------------------------------
:page-liquid:

// Set other global page attributes here
// -----------------------------------------------------------------------------


{% comment %} Liquid procedures
--------------------------------------------------------------- {% endcomment %}
{% capture set_env_entry_document %}themes/{{site.template.name}}/procedures/global/set_env_entry_document.proc{%endcapture%}


// NOTE: Initialize entry document paths
// -----------------------------------------------------------------------------
{% include {{set_env_entry_document}} init_folders=all %}

// Load tags and urls
// -----------------------------------------------------------------------------
include::{includedir}/attributes.asciidoc[tag=tags]
include::{includedir}/attributes.asciidoc[tag=urls]
include::{includedir}/attributes.asciidoc[tag=data]

// Additional Asciidoc page attributes goes here
// -----------------------------------------------------------------------------

++++
<!-- page_path:            {{page_path | debug}} -->
<!-- site.source:          {{site.source | debug}} -->
<!-- site.source.size:     {{site.source.size | debug}} -->
++++

lorem:sentences[5]
lorem:sentences[2]

== Themes

lorem:sentences[5]


== What's next

Hopefully you've enjoyed exploring some of the possibilities J1 offers for
managing themes. But much, much more can the J1 do for your website.

This was the last place to go for the roundtrip. More details of the most
common elements of Bootstrap can be found on the previewer for a theme. Have
a look at the link:{previewer-theme}[theme previewer, window="_blank"].

To make things real for your new site, go for *Web in a day*. This tutorial
guides you through all the steps how to build a website - your site using Jekyll 
and the template system J1. It's really a nice journey to *explore* and 
*learn* creating a static web - start from here: 
link:{kickstarter-web-in-a-day}[Web in a day, window="_blank"].


