---
title:                                  J1 Translators
tagline:                                integrate translation services
description:                            Managing google translator

tags:                                   [ App, Git, Github ]
index:                                  [ Google, Translator, Utility ]
categories:                             [ pages ]

permalink:                              /pages/public/translators/
regenerate:                             false

resources:                              [ lightbox ]
resource_options:
  - attic:
      padding_top:                      400
      padding_bottom:                   50
      opacity:                          0.5
      slides:
        - url:                          /assets/images/attics/romain-vignes-1920x1280.jpg
          alt:                          Photo by Romain Vignes on Unsplash
          badge:
            type:                       unsplash
            author:                     Romain Vignes
            href:                       https://unsplash.com/@rvignes
---

// Enable the Liquid Preprocessor
// -----------------------------------------------------------------------------
:page-liquid:

// Set other global page attributes here
// -----------------------------------------------------------------------------
//:my-asciidoc-attribute:

//  Load Liquid procedures
// -----------------------------------------------------------------------------
{% capture set_env_entry_document %}themes/{{site.template.name}}/procedures/global/set_env_entry_document.proc{%endcapture%}


// Initialize entry document environmental attributes
// -----------------------------------------------------------------------------
{% include {{set_env_entry_document}} %}

// Load tag, url and data attributes
// -----------------------------------------------------------------------------
include::{includedir}/attributes.asciidoc[tag=tags]
include::{includedir}/attributes.asciidoc[tag=urls]
include::{includedir}/attributes.asciidoc[tag=data]

// Set local page attributes
// -----------------------------------------------------------------------------
// :images-dir:                         {imagesdir}/path/to/page/images


// Page content
// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

// Include sub-documents
// -----------------------------------------------------------------------------

Speakers of a european language, with a good knowledge of English, have 
excellent chances to find all imaginable information on the Internet. This is 
because there are almost infinitely number or websites in these languages. 
But if users have only base knowledge of English or use a language that is not  
widespread on the Internet, they may depend on translations.

For many users, Google Translate is today a standard for translating words, 
texts or even entire web pages. To make understanding articles on J1 based 
websites a bit easier, an integration for Google Translate is available to 
support people for translations.

== Connectors

J1 Template support in general 2 types of integrations for 3rd party software
and services. Depending of their nature, 3rd party components are integrated
as:

* Application-based services using *connectors*
* API-based services using *modules*

Connectors offering a quite simple integration, because the service is 
integrated as an web application. This type of integration is used for e.g. 
*Disqus* (a commenting service) or the Google Translator.

For both integrations with J1 Template, an set of configuration parameters
are available. Because connectors integrate applications, the configuration
is quite limited.

== Google Translate

In late 2016, Google introduced neural machine translation (NMT) to 
Google Translate. The neural system translates whole sentences at a time, 
rather than analyse piece by piece. It uses broader context to help determine
the most relevant translation, which it then rearranges and adjusts to sound 
more like a real person. This could make translated paragraphs and articles 
smoother and easier to read.

[NOTE]
====
Google Translate does not longer apply *grammatical rules* on the translation 
since its algorithms are based on *statistical analysis* rather than traditional 
*rule-based* analysis.

However, if the source text is shorter, rule-based machine translations often 
perform better. This effect is particularly evident for translations like 
Chinese to English. This is specifically for Chinese because for this 
language its nearly impossible to interprete sentences as a whole based on an
statistical evaluation.
====

=== Accuracy

When Google Translate generates a translation, it looks for *patterns* in 
hundreds of millions of documents (if available) to decide on the best
translation. By detecting patterns in documents that have already been
already translated by *human translators*, Google Translate makes intelligent 
*guesses* on what an appropriate translation could be. 

[NOTE]
====
Because neural machine translations does *not* apply any *grammatical rules*, 
grammatical errors remain a major limitation to the accuracy of the results
provided.
====

Due to the differences between languages in complexity and nature, the accuracy
varies greatly between languages. Some languages produce better results than 
others. Typically, western languages such as English and Spanish are generally 
accurate, for other European languages the results are acceptable. But the 
accuracy for African and Asian language translations are often the poorest.

=== Technical backgroud

lorem:sentences[3]

lorem:sentences[3]

=== Configuration

Connectors are configured by the J1 Template configuration settings file 
*template_settings.yml* located in the folder *~/_data*. For translators the
following section configures then Google Translator:

.Configuration settings
[source, yaml]
----
  translation:
    enabled:                              true
    provider:                             google

    google:
<1>   layout:                             default
<2>   meta_data:                          [google-translate-customization]    
<3>   page_language:                      en
<4>   translation_languages:              [all]
----
<1> layout: fixed value set to *default*
<2> meta_data: additional meta key set in <head> section
<3> page_language: the language of the website to be translated
<4> translation_languages: fixed value set to *all*

==== Layout

lorem:sentences[3]

==== Meta data

lorem:sentences[3]

==== Page language

lorem:sentences[3]

==== Main languages

The number of available languages for Google Translator is growing constantly.
As mentioned, the quality of a translation depends on the number of documents
available written by native speakers. Find a relevant selection of *main*
languages supported below.

.Main languages for Google Translator
[cols="4,^2,4,^2", options="header", width="100%", role="table-responsive"]
|===============================================================================
|Language Name |Language Code |Language Name |Language Code

|Afrikaans |af |Irish |ga
|Albanian |sq |Italian |it
|Arabic |ar |Japanese |ja
|Azerbaijani |az |Kannada |kn
|Basque |eu |Korean |ko
|Bengali |bn |Latin |la
|Belarusian |be |Latvian |lv
|Bulgarian |bg |Lithuanian |lt
|Catalan |ca |Macedonian |mk
|Chinese Simplified |zh-CN |Malay |ms
|Chinese Traditional |zh-TW |Maltese |mt
|Croatian |hr |Norwegian |no
|Czech |cs |Persian |fa
|Danish |da |Polish |pl
|Dutch |nl |Portuguese |pt
|English |en |Romanian |ro
|Esperanto |eo |Russian |ru
|Estonian |et |Serbian |sr
|Filipino |tl |Slovak |sk
|Finnish |fi |Slovenian |sl
|French |fr |Spanish |es
|Galician |gl |Swahili |sw
|Georgian |ka |Swedish |sv
|German |de |Tamil |ta
|Greek |el |Telugu |te
|Gujarati |gu |Thai |th
|Haitian Creole |ht |Turkish |tr
|Hebrew |iw |Ukrainian |uk
|Hindi |hi |Urdu |ur
|Hungarian |hu |Vietnamese |vi
|Icelandic |is |Welsh |cy
|Indonesian |id |Yiddish |yi

|===============================================================================


=== Support Google Translator

lorem:sentences[3]

lorem:sentences[3]





